import { assertEquals, assertStringIncludes, assertThrows } from "@std/assert";
import type { FieldMeta, Metadata } from "../../src/objectdata/metadata.ts";
import { renderSchema } from "../../../tools/schema.ts";

function field(id: string, name: string, extra: Partial<FieldMeta> = {}): FieldMeta {
  return {
    id,
    name,
    label: name,
    category: "stats",
    type: "int",
    storage: "int",
    list: false,
    perLevel: false,
    column: 0,
    skin: false,
    use: [],
    specific: [],
    notSpecific: [],
    ...extra,
  };
}

function metadata(fields: Partial<Metadata["fields"]> = {}): Metadata {
  return {
    format: 1,
    game: "1.2.3.4",
    fields: { units: [], items: [], abilities: [], buffs: [], upgrades: [], ...fields },
    bases: { heroes: {}, units: {}, buildings: {}, items: {}, abilities: {}, buffs: {}, upgrades: {} },
  };
}

const MODULES = ["Ability", "Buff", "Building", "Hero", "Item", "Unit", "Upgrade"].map((name) =>
  `schema/generated/${name}Props.pkl`
);

Deno.test("renderSchema renders one abstract module per object class", () => {
  const out = renderSchema(metadata());
  assertEquals([...out.keys()].sort(), MODULES);
  const hero = out.get("schema/generated/HeroProps.pkl")!;
  assertStringIncludes(
    hero,
    "// GENERATED by `deno task gen` from cli/data/metadata.json (game 1.2.3.4) — do not edit.\n",
  );
  assertStringIncludes(hero, 'abstract module moonwell.generated.HeroProps\n\nextends "../objects/Object.pkl"\n');
});

Deno.test("renderSchema types each field by storage, list and level", () => {
  const out = renderSchema(metadata({
    abilities: [
      field("aint", "anInt"),
      field("abol", "aBool", { type: "bool" }),
      field("arel", "aReal", { type: "real", storage: "real" }),
      field("aunr", "anUnreal", { type: "unreal", storage: "unreal" }),
      field("astr", "aString", { type: "string", storage: "string" }),
      field("alst", "aList", { type: "unitList", storage: "string", list: true }),
      field("alvi", "levelInt", { perLevel: true, column: 1 }),
      field("alvb", "levelBool", { type: "bool", perLevel: true }),
      field("alvr", "levelReal", { type: "unreal", storage: "unreal", perLevel: true }),
      field("alvs", "levelString", { type: "string", storage: "string", perLevel: true }),
      field("alvl", "levelList", { type: "targetList", storage: "string", list: true, perLevel: true }),
      field("aenu", "anEnum", { type: "attackBits" }),
    ],
  }));
  const ability = out.get("schema/generated/AbilityProps.pkl")!;
  for (
    const line of [
      "anInt: Int?",
      "aBool: Boolean?",
      "aReal: Number?",
      "anUnreal: Number?",
      "aString: String?",
      "aList: (String|List<String>)?",
      "levelInt: (Int|List<Int>)?",
      "levelBool: (Boolean|List<Boolean>)?",
      "levelReal: (Number|List<Number>)?",
      "levelString: (String|List<String>)?",
      "levelList: (String|List<String>|List<List<String>>)?",
      "anEnum: Int?",
    ]
  ) assertStringIncludes(ability, `\n${line}\n`);
});

Deno.test("renderSchema writes the label, rawcode, category, type, level and skin into doc comments", () => {
  const out = renderSchema(metadata({
    units: [
      field("unam", "name", {
        label: "Name",
        category: "text",
        type: "string",
        storage: "string",
        skin: true,
        use: ["unit"],
      }),
    ],
    abilities: [field("Crs\u0000", "chanceToMiss", { label: "Chance to Miss", perLevel: true, column: 1 })],
    upgrades: [
      field("gnam", "name", { label: "Name", category: "text", type: "string", storage: "string", perLevel: true }),
    ],
  }));
  assertStringIncludes(
    out.get("schema/generated/UnitProps.pkl")!,
    "\n/// Name\n///\n/// Field `unam` (text, `string`). Skin field.\nname: String?\n",
  );
  assertStringIncludes(
    out.get("schema/generated/AbilityProps.pkl")!,
    "\n/// Chance to Miss\n///\n/// Field `Crs` (stats, `int`). Per level: a `List` sets levels 1, 2, ...\n" +
      "chanceToMiss: (Int|List<Int>)?\n",
  );
  assertStringIncludes(
    out.get("schema/generated/UpgradeProps.pkl")!,
    "/// Field `gnam` (text, `string`). Per level: a `List` sets levels 1, 2, ...\n",
  );
});

Deno.test("renderSchema documents list fields", () => {
  const out = renderSchema(metadata({
    units: [
      field("uabi", "normal", { label: "Normal", type: "abilityList", storage: "string", list: true, use: ["unit"] }),
    ],
  }));
  assertStringIncludes(
    out.get("schema/generated/UnitProps.pkl")!,
    "/// Field `uabi` (stats, `abilityList`). A comma-separated list: a `List<String>` is joined with commas.\n",
  );
});

Deno.test("renderSchema places unit fields by use and leaves ability-specific fields to properties", () => {
  const out = renderSchema(metadata({
    units: [
      field("uall", "everywhere", { use: ["unit", "hero", "building"] }),
      field("uher", "heroOnly", { use: ["hero"] }),
      field("ubld", "buildingOnly", { use: ["building"] }),
      field("uitm", "itemOnly", { use: ["item"] }),
    ],
    items: [field("iitm", "itemField", { use: ["item"] })],
    abilities: [
      field("acom", "common"),
      field("aexc", "excluded", { notSpecific: ["AHhb"] }),
      field("Hhb1", "amountHealed", { specific: ["AHhb"] }),
    ],
    buffs: [field("fbuf", "buffField")],
    upgrades: [field("gupg", "upgradeField")],
  }));
  const names = (module: string) =>
    [...out.get(`schema/generated/${module}Props.pkl`)!.matchAll(/^(\w+): /gm)].map((match) => match[1]);
  assertEquals(names("Unit"), ["everywhere"]);
  assertEquals(names("Hero"), ["everywhere", "heroOnly"]);
  assertEquals(names("Building"), ["buildingOnly", "everywhere"]);
  assertEquals(names("Item"), ["itemField"]);
  assertEquals(names("Ability"), ["common", "excluded"]);
  assertEquals(names("Buff"), ["buffField"]);
  assertEquals(names("Upgrade"), ["upgradeField"]);
});

Deno.test("renderSchema sorts fields by name and is deterministic", () => {
  const fields = [field("bzzz", "zeta"), field("baaa", "alpha"), field("bmmm", "Mu")];
  const first = renderSchema(metadata({ buffs: fields }));
  assertEquals(renderSchema(metadata({ buffs: [...fields].reverse() })), first);
  const text = first.get("schema/generated/BuffProps.pkl")!;
  assertEquals([...text.matchAll(/^(\w+): /gm)].map((match) => match[1]), ["Mu", "alpha", "zeta"]);
});

Deno.test("renderSchema fails on a friendly-name clash within a class", () => {
  const error = assertThrows(
    () =>
      renderSchema(
        metadata({ units: [field("uaaa", "same", { use: ["hero"] }), field("ubbb", "same", { use: ["hero"] })] }),
      ),
    Error,
  );
  assertStringIncludes(error.message, "HeroProps");
  assertStringIncludes(error.message, "uaaa");
  assertStringIncludes(error.message, "ubbb");
  // Different classes may share a name.
  renderSchema(
    metadata({ units: [field("uaaa", "same", { use: ["hero"] }), field("ubbb", "same", { use: ["unit"] })] }),
  );
});

Deno.test("renderSchema fails on reserved, keyword and invalid property names", () => {
  for (const name of ["id", "base", "source", "properties", "output", "class", "function", "2nd", "a-b", ""]) {
    const error = assertThrows(() => renderSchema(metadata({ buffs: [field("fxxx", name)] })), Error);
    assertStringIncludes(error.message, "fxxx");
  }
});
