import { assertEquals, assertRejects, assertThrows } from "@std/assert";
import { join } from "@std/path";
import {
  assertObjectIdsCurrent,
  OBJECT_IDS_FILE,
  objectIdsStatus,
  packId,
  refreshObjectIds,
  renderObjectIds,
  writeObjectIds,
} from "../../src/objectdata/ids.ts";
import { MoonwellError } from "../../src/shared/errors.ts";

const EMPTY = [
  "-- GENERATED by Moonwell from objects/**.pkl; do not edit.",
  "export heroes = {}",
  "export units = {}",
  "export buildings = {}",
  "export items = {}",
  "export abilities = {}",
  "export buffs = {}",
  "export upgrades = {}",
  "",
].join("\n");

async function withDir(run: (dir: string) => Promise<void>): Promise<void> {
  const dir = await Deno.makeTempDir();
  try {
    await run(dir);
  } finally {
    await Deno.remove(dir, { recursive: true });
  }
}

Deno.test("packId packs a rawcode big-endian, as FourCC and string.unpack('>I4') do", () => {
  assertEquals(packId("h000"), 1747988528);
  assertEquals(packId("h000"), 0x68303030);
  assertEquals(packId("A000"), 0x41303030);
  // Unsigned: ids starting with a byte of 0x80 or more stay positive (not reachable with ASCII ids, but defined).
  assertEquals(packId("\xff\0\0\0"), 0xff000000);
  assertThrows(() => packId("h00"), Error);
});

Deno.test("renderObjectIds writes every category in order, even when empty, with the exact header", () => {
  assertEquals(renderObjectIds([]), EMPTY);
});

Deno.test("renderObjectIds sorts keys within each category and comments each rawcode", () => {
  assertEquals(
    renderObjectIds([
      { category: "units", key: "captain", id: "h000" },
      { category: "abilities", key: "holy", id: "A001" },
      { category: "units", key: "Archer", id: "h002" },
      { category: "heroes", key: "paladin", id: "H000" },
      { category: "units", key: "archer", id: "h001" },
      { category: "upgrades", key: "swords", id: "R000" },
    ]),
    [
      "-- GENERATED by Moonwell from objects/**.pkl; do not edit.",
      "export heroes = {",
      "  paladin: 1211117616 -- H000",
      "}",
      "export units = {",
      "  Archer: 1747988530 -- h002",
      "  archer: 1747988529 -- h001",
      "  captain: 1747988528 -- h000",
      "}",
      "export buildings = {}",
      "export items = {}",
      "export abilities = {",
      "  holy: 1093677105 -- A001",
      "}",
      "export buffs = {}",
      "export upgrades = {",
      "  swords: 1378889776 -- R000",
      "}",
      "",
    ].join("\n"),
  );
});

Deno.test("objectIdsStatus: current, stale, or missing while the manifest has objects", async () => {
  await withDir(async (root) => {
    const withObjects = renderObjectIds([{ category: "units", key: "captain", id: "h000" }]);
    // No objects and no file passes, so projects from before objects keep passing check.
    assertEquals(await objectIdsStatus(root, EMPTY), "current");
    assertEquals(await objectIdsStatus(root, withObjects), "missing");
    assertEquals(await writeObjectIds(root, withObjects), true);
    assertEquals(await Deno.readTextFile(join(root, OBJECT_IDS_FILE)), withObjects);
    assertEquals(await writeObjectIds(root, withObjects), false);
    assertEquals(await objectIdsStatus(root, withObjects), "current");
    assertEquals(await objectIdsStatus(root, EMPTY), "stale");
    await writeObjectIds(root, EMPTY);
    assertEquals(await objectIdsStatus(root, EMPTY), "current");
  });
});

Deno.test("assertObjectIdsCurrent fails on a stale or missing file with the regenerate hint", async () => {
  await withDir(async (root) => {
    const withObjects = renderObjectIds([{ category: "units", key: "captain", id: "h000" }]);
    await assertObjectIdsCurrent(root, EMPTY);
    const missing = await assertRejects(() => assertObjectIdsCurrent(root, withObjects), MoonwellError);
    assertEquals(
      [missing.message, missing.file, missing.hint],
      [
        "The file is missing, but the manifest has objects.",
        "src/generated/objects.yue",
        "Run deno task build, test or dev to regenerate it.",
      ],
    );
    await writeObjectIds(root, EMPTY);
    const stale = await assertRejects(() => assertObjectIdsCurrent(root, withObjects), MoonwellError);
    assertEquals(
      [stale.message, stale.file, stale.hint],
      [
        "The file does not match the objects in the manifest.",
        "src/generated/objects.yue",
        "Run deno task build, test or dev to regenerate it.",
      ],
    );
    await writeObjectIds(root, withObjects);
    await assertObjectIdsCurrent(root, withObjects);
  });
});

Deno.test("objectIdsStatus reads a CRLF checkout (core.autocrlf) as the same module", async () => {
  await withDir(async (root) => {
    const withObjects = renderObjectIds([{ category: "units", key: "captain", id: "h000" }]);
    await writeObjectIds(root, withObjects.replaceAll("\n", "\r\n"));
    assertEquals(await objectIdsStatus(root, withObjects), "current");
    await assertObjectIdsCurrent(root, withObjects);
    // A lone CR is a real difference.
    await Deno.writeTextFile(join(root, OBJECT_IDS_FILE), withObjects.replaceAll("\n", "\r"));
    assertEquals(await objectIdsStatus(root, withObjects), "stale");
  });
});

Deno.test("refreshObjectIds writes only a stale or missing module, never an unneeded empty one", async () => {
  await withDir(async (root) => {
    const withObjects = renderObjectIds([{ category: "units", key: "captain", id: "h000" }]);
    const file = join(root, OBJECT_IDS_FILE);
    assertEquals(await refreshObjectIds(root, EMPTY), false);
    assertEquals(await Deno.stat(file).then(() => true, () => false), false, "no objects creates no file");
    assertEquals(await refreshObjectIds(root, withObjects), true);
    assertEquals(await Deno.readTextFile(file), withObjects);
    await Deno.writeTextFile(file, withObjects.replaceAll("\n", "\r\n"));
    assertEquals(await refreshObjectIds(root, withObjects), false, "a CRLF checkout is left alone");
    assertEquals(await refreshObjectIds(root, EMPTY), true, "removing every object empties the module");
    assertEquals(await Deno.readTextFile(file), EMPTY);
  });
});
