package editor

import (
	"strings"
	"testing"

	"github.com/mdlsvensson/moonwell/internal/manifest"
	"github.com/mdlsvensson/moonwell/internal/objects"
	"github.com/mdlsvensson/moonwell/internal/script"
	"github.com/mdlsvensson/moonwell/internal/war3/lua"
)

// Characters outside ASCII, as the bytes they are in a text.
const (
	fullWidthA = "\xef\xbc\xa1"     // U+FF21, above the surrogates and inside the basic plane
	beyond     = "\xf0\x9f\x98\x80" // U+1F600, beyond the basic plane
)

// api is a small API of a game: handle types that are not in the order of their parents, a function with a
// parameter that is a keyword of Lua, one that returns nothing, one that only Lua has, a constant and an array.
func api() *script.Natives {
	n := &script.Natives{
		GameVersion: "9.9.9",
		Types:       []script.NativeType{{Name: "agent", Extends: "handle"}, {Name: "unit", Extends: "widget"}, {Name: "widget", Extends: "agent"}},
		Functions: []script.NativeFunction{
			{
				Name: "CreateThing", Source: "common.j", Returns: "unit",
				Params: []script.NativeParam{{Name: "id", Type: "player"}, {Name: "end", Type: "real"}, {Name: "cb", Type: "code"}},
			},
			{Name: "DoNothing", Source: "blizzard.j", Returns: "nothing"},
			{Name: "FourCC", Source: "lua", Params: []script.NativeParam{{Name: "id", Type: "string"}}, Returns: "integer"},
		},
		Globals: []script.NativeGlobal{
			{Name: "MAX_THINGS", Source: "common.j", Type: "integer", Constant: true},
			{Name: "counts", Source: "blizzard.j", Type: "real", Array: true},
		},
	}
	n.Lua.Globals, n.Lua.Removed = []string{"print"}, []string{"io"}
	return n
}

func TestJASSTypesMapToLuaTypesHandleTypesKeepTheirNames(t *testing.T) {
	for jass, want := range map[string]string{
		"integer": "integer", "real": "number", "boolean": "boolean", "string": "string", "code": "function",
		"handle": "handle", "unit": "unit", "any": "any", "": "",
	} {
		if got := luaType(jass); got != want {
			t.Errorf("luaType(%q) = %q, want %q", jass, got, want)
		}
	}
}

func TestTheNativesDeclarationsDeclareClassesFunctionsAndGlobals(t *testing.T) {
	want := strings.Join([]string{
		"---@meta",
		"-- GENERATED by Moonwell from Warcraft III 9.9.9 (common.j, blizzard.j); do not edit.",
		"",
		// Parents first, so lua-language-server never sees an unknown parent.
		"---@class handle",
		"---@class agent: handle",
		"---@class widget: agent",
		"---@class unit: widget",
		"",
		"---@param id player",
		"---@param end_ number",
		"---@param cb function",
		"---@return unit",
		"function CreateThing(id, end_, cb) end",
		"",
		"function DoNothing() end",
		"",
		"---@param id string",
		"---@return integer",
		"function FourCC(id) end",
		"",
		"---@type integer",
		"MAX_THINGS = nil",
		"",
		"---@type number[]",
		"counts = nil",
		"",
	}, "\n")
	if got := renderNatives(api()); got != want {
		t.Errorf("renderNatives =\n%s", got)
	}
}

func TestTheNativesDeclarationsOfAnAPIThatHoldsNothingDeclareTheHandleClassAlone(t *testing.T) {
	want := "---@meta\n-- GENERATED by Moonwell from Warcraft III  (common.j, blizzard.j); do not edit.\n\n---@class handle\n"
	if got := renderNatives(&script.Natives{}); got != want {
		t.Errorf("renderNatives = %q", got)
	}
}

func TestEveryKeywordOfLuaIsNoNameOfAParameter(t *testing.T) {
	keywords := []string{
		"and", "break", "do", "else", "elseif", "end", "false", "for", "function", "goto", "if", "in", "local", "nil",
		"not", "or", "repeat", "return", "then", "true", "until", "while",
	}
	var params []script.NativeParam
	for _, keyword := range keywords {
		params = append(params, script.NativeParam{Name: keyword, Type: "integer"})
	}
	// A name that only starts as a keyword, and one in another letter case, are names.
	params = append(params, script.NativeParam{Name: "endX", Type: "integer"}, script.NativeParam{Name: "End", Type: "integer"})
	declared := renderNatives(&script.Natives{Functions: []script.NativeFunction{{Name: "F", Params: params, Returns: "nothing"}}})
	contains(t, declared, "function F("+strings.Join(keywords, "_, ")+"_, endX, End) end\n")
	for _, keyword := range keywords {
		contains(t, declared, "---@param "+keyword+"_ integer\n")
	}
}

func TestTheHandleClassesAreDeclaredParentsFirstAndSiblingsInByteOrder(t *testing.T) {
	// A type whose parent no type line reaches from handle is not declared: nothing leads to it.
	n := &script.Natives{Types: []script.NativeType{
		{Name: "widget", Extends: "agent"}, {Name: "b" + beyond, Extends: "handle"}, {Name: "b" + fullWidthA, Extends: "handle"},
		{Name: "agent", Extends: "handle"}, {Name: "Zed", Extends: "handle"}, {Name: "orphan", Extends: "nowhere"},
		{Name: "ability", Extends: "agent"},
	}}
	want := []string{
		"---@class handle", "---@class Zed: handle", "---@class agent: handle", "---@class ability: agent",
		"---@class widget: agent", "---@class b" + fullWidthA + ": handle", "---@class b" + beyond + ": handle",
	}
	// The classes stand between the three lines of the head and the last line break.
	declared := renderNatives(n)
	if _, classes, found := strings.Cut(declared, "do not edit.\n\n"); !found || classes != strings.Join(want, "\n")+"\n" {
		t.Errorf("renderNatives =\n%s", declared)
	}
}

func TestTheRuntimeDeclarationsDeclareTheModulesHooksAndRequire(t *testing.T) {
	declarations := runtimeDeclarations
	if !strings.HasPrefix(declarations, "---@meta moonwell\n") || !strings.HasSuffix(declarations, "\nreturn moonwell\n") {
		t.Errorf("runtimeDeclarations =\n%s", declarations)
	}
	// A YueScript function returns its last expression, so a hook's callback may return anything.
	for _, hook := range []string{"before_config", "on_config", "before_main", "on_main"} {
		contains(t, declarations, "---@param fn fun(): ...\nfunction moonwell."+hook+"(fn) end\n")
	}
	contains(t, declarations, "function moonwell.format_error(message) end\n",
		// .luarc.json turns off the package library, which would otherwise remove require.
		"---@param name string\n---@return any\nfunction require(name) end\n")
	// Every line is a comment, a statement of the module or blank. A line of any other kind is no Lua, and the
	// editor then takes nothing from the file.
	for number, line := range strings.Split(strings.TrimSuffix(declarations, "\n"), "\n") {
		isComment := strings.HasPrefix(line, "---") || strings.HasPrefix(line, "-- ")
		isStatement := line == "local moonwell = {}" || line == "return moonwell" ||
			strings.HasPrefix(line, "function ") && strings.HasSuffix(line, ") end")
		if line != "" && !isComment && !isStatement {
			t.Errorf("line %d of the runtime declarations is neither a comment nor a statement: %q", number+1, line)
		}
	}
}

func resolved() []objects.Resolved {
	return []objects.Resolved{
		{Category: "units", Key: "captain", ID: "h000"},
		{Category: "units", Key: "archer", ID: "h001"},
		{Category: "abilities", Key: "holyLight", ID: "A000"},
	}
}

func TestTheObjectDeclarationsDeclareEveryCategoryKeysSortedWithRawcodes(t *testing.T) {
	declarations := renderObjects(resolved())
	if !strings.HasPrefix(declarations, "---@meta generated.objects\n---@diagnostic disable: missing-fields\n") {
		t.Errorf("renderObjects =\n%s", declarations)
	}
	contains(t, declarations,
		"---@class generated.objects.units\n---@field archer integer h001\n---@field captain integer h000\n",
		"---@class generated.objects.heroes\n\n",
		"---@type generated.objects.abilities\nobjects.abilities = {}\n",
		"return objects\n")
	if got := strings.Count(declarations, "---@class "); got != len(manifest.Categories) {
		t.Errorf("%d classes for %d categories", got, len(manifest.Categories))
	}
}

func TestTheObjectDeclarationsOfNoObjectsDeclareEveryCategoryEmpty(t *testing.T) {
	want := "---@meta generated.objects\n---@diagnostic disable: missing-fields\n" +
		"-- GENERATED by Moonwell from objects/**.pkl; do not edit.\n\n"
	for _, category := range manifest.Categories {
		want += "---@class generated.objects." + string(category) + "\n\n"
	}
	want += "local objects = {}\n\n"
	for _, category := range manifest.Categories {
		want += "---@type generated.objects." + string(category) + "\nobjects." + string(category) + " = {}\n\n"
	}
	want += "return objects\n"
	if got := renderObjects(nil); got != want {
		t.Errorf("renderObjects(nil) =\n%s", got)
	}
}

func TestTheObjectDeclarationsSortKeysByBytesAndKeepTheOrderOfEqualOnes(t *testing.T) {
	declarations := renderObjects([]objects.Resolved{
		{Category: "items", Key: "k" + beyond, ID: "I000"}, {Category: "items", Key: "k" + fullWidthA, ID: "I001"},
		{Category: "items", Key: "same", ID: "I002"}, {Category: "items", Key: "Zed", ID: "I003"},
		{Category: "items", Key: "same", ID: "I004"}, {Category: "items", Key: "_low", ID: "I005"},
	})
	contains(t, declarations, "---@class generated.objects.items\n"+
		"---@field Zed integer I003\n---@field _low integer I005\n"+
		"---@field k"+fullWidthA+" integer I001\n---@field k"+beyond+" integer I000\n"+
		"---@field same integer I002\n---@field same integer I004\n\n")
}

func TestTheMapDeclarationsDeclareTheMapsGlobalsAndFunctions(t *testing.T) {
	globals := &lua.MapGlobals{Globals: []lua.Global{{Name: "udg_Score", Type: "integer"}}, Functions: []string{"InitGlobals"}}
	want := "---@meta\n-- GENERATED by Moonwell from maps/map.w3x/war3map.lua; do not edit.\n\n" +
		"---@type integer\nudg_Score = nil\n\nfunction InitGlobals() end\n"
	if got := renderMap(globals, "maps/map.w3x/war3map.lua"); got != want {
		t.Errorf("renderMap =\n%s", got)
	}
}

func TestTheMapDeclarationsOfAScriptThatDefinesNothingNameTheScript(t *testing.T) {
	want := "---@meta\n-- GENERATED by Moonwell from maps/map.w3x/war3map.lua; do not edit.\n"
	if got := renderMap(&lua.MapGlobals{}, "maps/map.w3x/war3map.lua"); got != want {
		t.Errorf("renderMap = %q", got)
	}
}

func TestWithoutASourceMapTheMapDeclarationsSaySoAndDeclareNothing(t *testing.T) {
	want := "---@meta\n-- GENERATED by Moonwell: there is no maps/map.w3x/war3map.lua yet; save the map in World Editor.\n"
	if got := renderMap(nil, "maps/map.w3x/war3map.lua"); got != want {
		t.Errorf("renderMap =\n%s", got)
	}
}
