package editor

import (
	"slices"
	"strings"

	"github.com/mdlsvensson/moonwell/internal/manifest"
	"github.com/mdlsvensson/moonwell/internal/objects"
	"github.com/mdlsvensson/moonwell/internal/script"
	"github.com/mdlsvensson/moonwell/internal/war3/lua"
)

var luaTypes = map[string]string{
	"integer": "integer",
	"real":    "number",
	"boolean": "boolean",
	"string":  "string",
	"code":    "function",
}

var luaKeywords = []string{
	"and", "break", "do", "else", "elseif", "end", "false", "for", "function", "goto", "if", "in", "local", "nil", "not",
	"or", "repeat", "return", "then", "true", "until", "while",
}

func luaType(jassType string) string {
	if named, ok := luaTypes[jassType]; ok {
		return named
	}
	return jassType
}

func renderNatives(n *script.Natives) string {
	lines := []string{
		"---@meta",
		"-- GENERATED by Moonwell from Warcraft III " + n.GameVersion + " (common.j, blizzard.j); do not edit.",
		"",
	}
	lines = append(lines, renderClasses(n.Types)...)
	lines = append(lines, "")
	for _, function := range n.Functions {
		lines = append(lines, renderFunction(function)...)
	}
	for _, global := range n.Globals {
		lines = append(lines, renderGlobal(global)...)
	}
	return strings.Join(lines, "\n")
}

func renderClasses(types []script.NativeType) []string {
	children := map[string][]string{}
	for _, handleType := range types {
		children[handleType.Extends] = append(children[handleType.Extends], handleType.Name)
	}
	for _, names := range children {
		slices.Sort(names)
	}
	return append([]string{"---@class handle"}, subclassesOf("handle", children)...)
}

func subclassesOf(parent string, children map[string][]string) []string {
	var lines []string
	for _, name := range children[parent] {
		lines = append(lines, "---@class "+name+": "+parent)
		lines = append(lines, subclassesOf(name, children)...)
	}
	return lines
}

func renderFunction(function script.NativeFunction) []string {
	var lines []string
	params := make([]string, len(function.Params))
	for i, param := range function.Params {
		params[i] = paramName(param.Name)
		lines = append(lines, "---@param "+params[i]+" "+luaType(param.Type))
	}
	if function.Returns != "nothing" {
		lines = append(lines, "---@return "+luaType(function.Returns))
	}
	return append(lines, "function "+function.Name+"("+strings.Join(params, ", ")+") end", "")
}

func paramName(name string) string {
	if slices.Contains(luaKeywords, name) {
		return name + "_"
	}
	return name
}

func renderGlobal(global script.NativeGlobal) []string {
	array := ""
	if global.Array {
		array = "[]"
	}
	return []string{"---@type " + luaType(global.Type) + array, global.Name + " = nil", ""}
}

const runtimeDeclarations = "---@meta moonwell\n" +
	"-- GENERATED by Moonwell; do not edit.\n" +
	"\n" +
	"---The Moonwell runtime. Hooks of one kind run in the order they were added. A failing hook prints its error\n" +
	"---with the .yue file and line, and the other hooks still run.\n" +
	"local moonwell = {}\n" +
	"\n" +
	"---Adds `fn` to run when the game calls config(), before World Editor's config() sets up players, forces and\n" +
	"---start locations.\n" +
	"---@param fn fun(): ...\n" +
	"function moonwell.before_config(fn) end\n" +
	"\n" +
	"---Adds `fn` to run when the game calls config(), after World Editor's config() has set up players and forces.\n" +
	"---@param fn fun(): ...\n" +
	"function moonwell.on_config(fn) end\n" +
	"\n" +
	"---Adds `fn` to run when the game calls main(), before World Editor's main() creates preplaced units and runs\n" +
	"---the initialization triggers.\n" +
	"---@param fn fun(): ...\n" +
	"function moonwell.before_main(fn) end\n" +
	"\n" +
	"---Adds `fn` to run when the game calls main(), after World Editor's main(): preplaced units exist and the\n" +
	"---initialization triggers have run.\n" +
	"---@param fn fun(): ...\n" +
	"function moonwell.on_main(fn) end\n" +
	"\n" +
	"---Rewrites war3map.lua line numbers in an error message to the source file and line (src/*.yue or\n" +
	"---lua/*.lua); for a minified YueScript module, to the file only.\n" +
	"---@param message string\n" +
	"---@return string\n" +
	"function moonwell.format_error(message) end\n" +
	"\n" +
	"---Loads a bundled module by its dotted name, such as \"heroes.captain\" or \"moonwell\". The Moonwell runtime\n" +
	"---defines it: the game's Lua has no package library, which .luarc.json turns off along with LuaLS's own require.\n" +
	"---@param name string\n" +
	"---@return any\n" +
	"function require(name) end\n" +
	"\n" +
	"return moonwell\n"

func renderObjects(resolved []objects.Resolved) string {
	lines := []string{
		"---@meta generated.objects",
		"---@diagnostic disable: missing-fields",
		"-- GENERATED by Moonwell from objects/**.pkl; do not edit.",
		"",
	}
	for _, category := range manifest.Categories {
		lines = append(lines, renderCategoryClass(category, resolved)...)
	}
	lines = append(lines, "local objects = {}", "")
	for _, category := range manifest.Categories {
		lines = append(lines, "---@type generated.objects."+string(category), "objects."+string(category)+" = {}", "")
	}
	return strings.Join(append(lines, "return objects", ""), "\n")
}

func renderCategoryClass(category manifest.Category, resolved []objects.Resolved) []string {
	var entries []objects.Resolved
	for _, object := range resolved {
		if object.Category == category {
			entries = append(entries, object)
		}
	}
	slices.SortStableFunc(entries, func(a, b objects.Resolved) int { return strings.Compare(a.Key, b.Key) })
	lines := []string{"---@class generated.objects." + string(category)}
	for _, object := range entries {
		lines = append(lines, "---@field "+object.Key+" integer "+object.ID)
	}
	return append(lines, "")
}

func renderMap(globals *lua.MapGlobals, source string) string {
	if globals == nil {
		return "---@meta\n-- GENERATED by Moonwell: there is no " + source + " yet; save the map in World Editor.\n"
	}
	lines := []string{"---@meta", "-- GENERATED by Moonwell from " + source + "; do not edit.", ""}
	for _, global := range globals.Globals {
		lines = append(lines, "---@type "+global.Type, global.Name+" = nil", "")
	}
	for _, function := range globals.Functions {
		lines = append(lines, "function "+function+"() end", "")
	}
	return strings.Join(lines, "\n")
}
