// Package editor writes the files a code editor reads: the declarations lua-language-server learns the game's API
// from, the macro module, the libraries as Lua, and the settings files of a project made by an older Moonwell.
package editor

import (
	"slices"
	"strings"

	"github.com/mdlsvensson/moonwell/internal/luasrc"
	"github.com/mdlsvensson/moonwell/internal/natives"
	"github.com/mdlsvensson/moonwell/internal/objects"
	"github.com/mdlsvensson/moonwell/internal/text"
)

var luaTypes = map[string]string{
	"integer": "integer",
	"real":    "number",
	"boolean": "boolean",
	"string":  "string",
	"code":    "function",
}

var luaKeywords = []string{
	"and", "break", "do", "else", "elseif", "end", "false", "for", "function", "goto", "if", "in", "local", "nil", "not",
	"or", "repeat", "return", "then", "true", "until", "while",
}

// LuaType is the lua-language-server type for a JASS type. Handle types, and the Lua types of the Lua-only
// functions, pass through.
func LuaType(jassType string) string {
	if luaType, ok := luaTypes[jassType]; ok {
		return luaType
	}
	return jassType
}

// paramName is a JASS parameter name as a Lua identifier: a Lua keyword gets a trailing underscore.
func paramName(name string) string {
	if slices.Contains(luaKeywords, name) {
		return name + "_"
	}
	return name
}

// classLines declares the handle classes, each after its parent, starting from `handle` (which no `type` line
// declares).
func classLines(n *natives.Natives) []string {
	children := map[string][]string{}
	for _, handleType := range n.Types {
		children[handleType.Extends] = append(children[handleType.Extends], handleType.Name)
	}
	lines := []string{"---@class handle"}
	var visit func(parent string)
	visit = func(parent string) {
		names := slices.Clone(children[parent])
		text.Sort(names)
		for _, name := range names {
			lines = append(lines, "---@class "+name+": "+parent)
			visit(name)
		}
	}
	visit("handle")
	return lines
}

// RenderNatives is .moonwell/types/natives.d.lua.
func RenderNatives(n *natives.Natives) string {
	out := []string{
		"---@meta",
		"-- GENERATED by Moonwell from Warcraft III " + n.GameVersion + " (common.j, blizzard.j); do not edit.",
		"",
	}
	out = append(out, classLines(n)...)
	out = append(out, "")
	for _, function := range n.Functions {
		params := make([]string, len(function.Params))
		for i, param := range function.Params {
			params[i] = paramName(param.Name)
			out = append(out, "---@param "+params[i]+" "+LuaType(param.Type))
		}
		if function.Returns != "nothing" {
			out = append(out, "---@return "+LuaType(function.Returns))
		}
		out = append(out, "function "+function.Name+"("+strings.Join(params, ", ")+") end", "")
	}
	for _, global := range n.Globals {
		array := ""
		if global.Array {
			array = "[]"
		}
		out = append(out, "---@type "+LuaType(global.Type)+array, global.Name+" = nil", "")
	}
	return strings.Join(out, "\n")
}

// RuntimeDeclarations is .moonwell/types/moonwell.d.lua: the runtime module (runtime/moonwell.lua) as gameplay code
// sees it.
var RuntimeDeclarations = strings.Join([]string{
	"---@meta moonwell",
	"-- GENERATED by Moonwell; do not edit.",
	"",
	"---The Moonwell runtime. Hooks of one kind run in the order they were added. A failing hook prints its error",
	"---with the .yue file and line, and the other hooks still run.",
	"local moonwell = {}",
	"",
	"---Adds `fn` to run when the game calls config(), before World Editor's config() sets up players, forces and",
	"---start locations.",
	"---@param fn fun(): ...",
	"function moonwell.before_config(fn) end",
	"",
	"---Adds `fn` to run when the game calls config(), after World Editor's config() has set up players and forces.",
	"---@param fn fun(): ...",
	"function moonwell.on_config(fn) end",
	"",
	"---Adds `fn` to run when the game calls main(), before World Editor's main() creates preplaced units and runs",
	"---the initialization triggers.",
	"---@param fn fun(): ...",
	"function moonwell.before_main(fn) end",
	"",
	"---Adds `fn` to run when the game calls main(), after World Editor's main(): preplaced units exist and the",
	"---initialization triggers have run.",
	"---@param fn fun(): ...",
	"function moonwell.on_main(fn) end",
	"",
	"---Rewrites war3map.lua line numbers in an error message to the source file and line (src/*.yue or",
	"---lua/*.lua); for a minified YueScript module, to the file only.",
	"---@param message string",
	"---@return string",
	"function moonwell.format_error(message) end",
	"",
	`---Loads a bundled module by its dotted name, such as "heroes.captain" or "moonwell". The Moonwell runtime`,
	"---defines it: the game's Lua has no package library, which .luarc.json turns off along with LuaLS's own require.",
	"---@param name string",
	"---@return any",
	"function require(name) end",
	"",
	"return moonwell",
	"",
}, "\n")

// RenderObjects is .moonwell/types/objects.d.lua: src/generated/objects.yue as gameplay code sees it.
func RenderObjects(resolved []objects.Resolved) string {
	out := []string{
		"---@meta generated.objects",
		// `objects.units = {}` below would otherwise warn that the class's fields are missing.
		"---@diagnostic disable: missing-fields",
		"-- GENERATED by Moonwell from objects/**.pkl; do not edit.",
		"",
	}
	for _, category := range objects.Categories {
		out = append(out, "---@class generated.objects."+string(category))
		var entries []objects.Resolved
		for _, object := range resolved {
			if object.Category == category {
				entries = append(entries, object)
			}
		}
		slices.SortStableFunc(entries, func(a, b objects.Resolved) int { return text.Compare(a.Key, b.Key) })
		for _, object := range entries {
			out = append(out, "---@field "+object.Key+" integer "+object.ID)
		}
		out = append(out, "")
	}
	out = append(out, "local objects = {}", "")
	for _, category := range objects.Categories {
		out = append(out, "---@type generated.objects."+string(category), "objects."+string(category)+" = {}", "")
	}
	out = append(out, "return objects", "")
	return strings.Join(out, "\n")
}

// RenderMap is .moonwell/types/map.d.lua. source is the war3map.lua the globals came from, as the project names it;
// globals is nil when there is no such file.
func RenderMap(globals *luasrc.MapGlobals, source string) string {
	if globals == nil {
		return "---@meta\n-- GENERATED by Moonwell: there is no " + source + " yet; save the map in World Editor.\n"
	}
	out := []string{"---@meta", "-- GENERATED by Moonwell from " + source + "; do not edit.", ""}
	for _, global := range globals.Globals {
		out = append(out, "---@type "+global.Type, global.Name+" = nil", "")
	}
	for _, function := range globals.Functions {
		out = append(out, "function "+function+"() end", "")
	}
	return strings.Join(out, "\n")
}
