package editor

import (
	"slices"
	"strings"

	"github.com/mdlsvensson/moonwell/internal/manifest"
	"github.com/mdlsvensson/moonwell/internal/objects"
	"github.com/mdlsvensson/moonwell/internal/script"
	"github.com/mdlsvensson/moonwell/internal/war3/lua"
)

// luaTypes is the lua-language-server type of each JASS type that is no handle type.
var luaTypes = map[string]string{
	"integer": "integer",
	"real":    "number",
	"boolean": "boolean",
	"string":  "string",
	"code":    "function",
}

// luaKeywords are the words no parameter of a Lua function can be named.
var luaKeywords = []string{
	"and", "break", "do", "else", "elseif", "end", "false", "for", "function", "goto", "if", "in", "local", "nil", "not",
	"or", "repeat", "return", "then", "true", "until", "while",
}

// luaType is the lua-language-server type for a JASS type. Handle types, and the Lua types of the functions only
// Lua has, pass through.
func luaType(jassType string) string {
	if luaType, ok := luaTypes[jassType]; ok {
		return luaType
	}
	return jassType
}

// renderNatives is .moonwell/types/natives.d.lua: the handle types as classes, then every function, then every
// global, in the order the API lists them.
func renderNatives(n *script.Natives) string {
	lines := []string{
		"---@meta",
		"-- GENERATED by Moonwell from Warcraft III " + n.GameVersion + " (common.j, blizzard.j); do not edit.",
		"",
	}
	lines = append(lines, classLines(n.Types)...)
	lines = append(lines, "")
	for _, function := range n.Functions {
		lines = append(lines, functionLines(function)...)
	}
	for _, global := range n.Globals {
		lines = append(lines, globalLines(global)...)
	}
	return strings.Join(lines, "\n")
}

// classLines declares the handle classes, each after its parent, starting from `handle`, which no type of the API
// declares. The types of one parent are in the order of their names' bytes.
func classLines(types []script.NativeType) []string {
	children := map[string][]string{}
	for _, handleType := range types {
		children[handleType.Extends] = append(children[handleType.Extends], handleType.Name)
	}
	for _, names := range children {
		slices.Sort(names)
	}
	return append([]string{"---@class handle"}, classesBelow("handle", children)...)
}

// classesBelow declares the classes that extend parent, each followed by the classes below it.
func classesBelow(parent string, children map[string][]string) []string {
	var lines []string
	for _, name := range children[parent] {
		lines = append(lines, "---@class "+name+": "+parent)
		lines = append(lines, classesBelow(name, children)...)
	}
	return lines
}

// functionLines declares one function: a line for each parameter, one for what it returns, the function with an
// empty body, and a blank line.
func functionLines(function script.NativeFunction) []string {
	var lines []string
	params := make([]string, len(function.Params))
	for i, param := range function.Params {
		params[i] = paramName(param.Name)
		lines = append(lines, "---@param "+params[i]+" "+luaType(param.Type))
	}
	if function.Returns != "nothing" {
		lines = append(lines, "---@return "+luaType(function.Returns))
	}
	return append(lines, "function "+function.Name+"("+strings.Join(params, ", ")+") end", "")
}

// paramName is a JASS parameter name as a Lua identifier: a Lua keyword gets a trailing underscore.
func paramName(name string) string {
	if slices.Contains(luaKeywords, name) {
		return name + "_"
	}
	return name
}

// globalLines declares one global by its type, and a blank line.
func globalLines(global script.NativeGlobal) []string {
	array := ""
	if global.Array {
		array = "[]"
	}
	return []string{"---@type " + luaType(global.Type) + array, global.Name + " = nil", ""}
}

// runtimeDeclarations is .moonwell/types/moonwell.d.lua: the runtime module (runtime/moonwell.lua) as gameplay
// code sees it.
const runtimeDeclarations = "---@meta moonwell\n" +
	"-- GENERATED by Moonwell; do not edit.\n" +
	"\n" +
	"---The Moonwell runtime. Hooks of one kind run in the order they were added. A failing hook prints its error\n" +
	"---with the .yue file and line, and the other hooks still run.\n" +
	"local moonwell = {}\n" +
	"\n" +
	"---Adds `fn` to run when the game calls config(), before World Editor's config() sets up players, forces and\n" +
	"---start locations.\n" +
	"---@param fn fun(): ...\n" +
	"function moonwell.before_config(fn) end\n" +
	"\n" +
	"---Adds `fn` to run when the game calls config(), after World Editor's config() has set up players and forces.\n" +
	"---@param fn fun(): ...\n" +
	"function moonwell.on_config(fn) end\n" +
	"\n" +
	"---Adds `fn` to run when the game calls main(), before World Editor's main() creates preplaced units and runs\n" +
	"---the initialization triggers.\n" +
	"---@param fn fun(): ...\n" +
	"function moonwell.before_main(fn) end\n" +
	"\n" +
	"---Adds `fn` to run when the game calls main(), after World Editor's main(): preplaced units exist and the\n" +
	"---initialization triggers have run.\n" +
	"---@param fn fun(): ...\n" +
	"function moonwell.on_main(fn) end\n" +
	"\n" +
	"---Rewrites war3map.lua line numbers in an error message to the source file and line (src/*.yue or\n" +
	"---lua/*.lua); for a minified YueScript module, to the file only.\n" +
	"---@param message string\n" +
	"---@return string\n" +
	"function moonwell.format_error(message) end\n" +
	"\n" +
	"---Loads a bundled module by its dotted name, such as \"heroes.captain\" or \"moonwell\". The Moonwell runtime\n" +
	"---defines it: the game's Lua has no package library, which .luarc.json turns off along with LuaLS's own require.\n" +
	"---@param name string\n" +
	"---@return any\n" +
	"function require(name) end\n" +
	"\n" +
	"return moonwell\n"

// renderObjects is .moonwell/types/objects.d.lua: src/generated/objects.yue as gameplay code sees it. It declares
// a class for every category in order, with a field for each object, sorted by the bytes of the keys, and then
// the module's table of each category. It reads only the category, the key and the id of an object.
func renderObjects(resolved []objects.Resolved) string {
	lines := []string{
		"---@meta generated.objects",
		// `objects.units = {}` below would otherwise warn that the class's fields are missing.
		"---@diagnostic disable: missing-fields",
		"-- GENERATED by Moonwell from objects/**.pkl; do not edit.",
		"",
	}
	for _, category := range manifest.Categories {
		lines = append(lines, categoryClass(category, resolved)...)
	}
	lines = append(lines, "local objects = {}", "")
	for _, category := range manifest.Categories {
		lines = append(lines, "---@type generated.objects."+string(category), "objects."+string(category)+" = {}", "")
	}
	return strings.Join(append(lines, "return objects", ""), "\n")
}

// categoryClass declares the class of one category: a field for each of its objects, with the rawcode as the
// field's description, and a blank line.
func categoryClass(category manifest.Category, resolved []objects.Resolved) []string {
	var entries []objects.Resolved
	for _, object := range resolved {
		if object.Category == category {
			entries = append(entries, object)
		}
	}
	slices.SortStableFunc(entries, func(a, b objects.Resolved) int { return strings.Compare(a.Key, b.Key) })
	lines := []string{"---@class generated.objects." + string(category)}
	for _, object := range entries {
		lines = append(lines, "---@field "+object.Key+" integer "+object.ID)
	}
	return append(lines, "")
}

// renderMap is .moonwell/types/map.d.lua. source is the war3map.lua the globals came from, as the project names
// it; globals is nil when the map has no such file.
func renderMap(globals *lua.MapGlobals, source string) string {
	if globals == nil {
		return "---@meta\n-- GENERATED by Moonwell: there is no " + source + " yet; save the map in World Editor.\n"
	}
	lines := []string{"---@meta", "-- GENERATED by Moonwell from " + source + "; do not edit.", ""}
	for _, global := range globals.Globals {
		lines = append(lines, "---@type "+global.Type, global.Name+" = nil", "")
	}
	for _, function := range globals.Functions {
		lines = append(lines, "function "+function+"() end", "")
	}
	return strings.Join(lines, "\n")
}
