package editor_test

import (
	"errors"
	"os"
	"path/filepath"
	"reflect"
	"runtime"
	"slices"
	"strings"
	"testing"

	moonwell "github.com/mdlsvensson/moonwell"
	"github.com/mdlsvensson/moonwell/internal/bundle"
	"github.com/mdlsvensson/moonwell/internal/diag"
	"github.com/mdlsvensson/moonwell/internal/editor"
	"github.com/mdlsvensson/moonwell/internal/fsx"
	"github.com/mdlsvensson/moonwell/internal/luasrc"
	"github.com/mdlsvensson/moonwell/internal/natives"
	"github.com/mdlsvensson/moonwell/internal/objects"
	"github.com/mdlsvensson/moonwell/internal/ordered"
	"github.com/mdlsvensson/moonwell/internal/testkit"
)

func asError(t *testing.T, err error, what string) *diag.Error {
	t.Helper()
	var e *diag.Error
	if !errors.As(err, &e) {
		t.Fatalf("%s: got %v, want a *diag.Error", what, err)
	}
	return e
}

func read(t *testing.T, root, path string) string {
	t.Helper()
	data, err := os.ReadFile(filepath.Join(root, filepath.FromSlash(path)))
	if err != nil {
		t.Fatal(err)
	}
	return string(data)
}

func contains(t *testing.T, text string, parts ...string) {
	t.Helper()
	for _, part := range parts {
		if !strings.Contains(text, part) {
			t.Errorf("%q is missing from\n%s", part, text)
		}
	}
}

func api() *natives.Natives {
	n := &natives.Natives{
		GameVersion: "9.9.9",
		Types:       []natives.Type{{Name: "agent", Extends: "handle"}, {Name: "unit", Extends: "widget"}, {Name: "widget", Extends: "agent"}},
		Functions: []natives.Function{
			{
				Name: "CreateThing", Source: "common.j", Returns: "unit",
				Params: []natives.Param{{Name: "id", Type: "player"}, {Name: "end", Type: "real"}, {Name: "cb", Type: "code"}},
			},
			{Name: "DoNothing", Source: "blizzard.j", Returns: "nothing"},
			{Name: "FourCC", Source: "lua", Params: []natives.Param{{Name: "id", Type: "string"}}, Returns: "integer"},
		},
		Globals: []natives.Global{
			{Name: "MAX_THINGS", Source: "common.j", Type: "integer", Constant: true},
			{Name: "counts", Source: "blizzard.j", Type: "real", Array: true},
		},
	}
	n.Lua.Globals, n.Lua.Removed = []string{"print"}, []string{"io"}
	return n
}

func TestJASSTypesMapToLuaTypesHandleTypesKeepTheirNames(t *testing.T) {
	for jass, lua := range map[string]string{
		"integer": "integer", "real": "number", "boolean": "boolean", "string": "string", "code": "function",
		"handle": "handle", "unit": "unit", "any": "any",
	} {
		if got := editor.LuaType(jass); got != lua {
			t.Errorf("LuaType(%s) = %s", jass, got)
		}
	}
}

func TestTheNativesDeclarationsDeclareClassesFunctionsAndGlobals(t *testing.T) {
	want := strings.Join([]string{
		"---@meta",
		"-- GENERATED by Moonwell from Warcraft III 9.9.9 (common.j, blizzard.j); do not edit.",
		"",
		// Parents first, so lua-language-server never sees an unknown parent.
		"---@class handle",
		"---@class agent: handle",
		"---@class widget: agent",
		"---@class unit: widget",
		"",
		"---@param id player",
		"---@param end_ number",
		"---@param cb function",
		"---@return unit",
		"function CreateThing(id, end_, cb) end",
		"",
		"function DoNothing() end",
		"",
		"---@param id string",
		"---@return integer",
		"function FourCC(id) end",
		"",
		"---@type integer",
		"MAX_THINGS = nil",
		"",
		"---@type number[]",
		"counts = nil",
		"",
	}, "\n")
	if got := editor.RenderNatives(api()); got != want {
		t.Errorf("RenderNatives =\n%s", got)
	}
}

func TestTheRuntimeDeclarationsDeclareTheModulesHooksAndRequire(t *testing.T) {
	declarations := editor.RuntimeDeclarations
	if !strings.HasPrefix(declarations, "---@meta moonwell\n") || !strings.HasSuffix(declarations, "\nreturn moonwell\n") {
		t.Errorf("RuntimeDeclarations =\n%s", declarations)
	}
	// A YueScript function returns its last expression, so a hook's callback may return anything.
	for _, hook := range []string{"before_config", "on_config", "before_main", "on_main"} {
		contains(t, declarations, "---@param fn fun(): ...\nfunction moonwell."+hook+"(fn) end\n")
	}
	contains(t, declarations, "function moonwell.format_error(message) end\n",
		// .luarc.json turns off the package library, which would otherwise remove require.
		"---@param name string\n---@return any\nfunction require(name) end\n")
}

func resolved() []objects.Resolved {
	return []objects.Resolved{
		{Category: "units", Key: "captain", ID: "h000"},
		{Category: "units", Key: "archer", ID: "h001"},
		{Category: "abilities", Key: "holyLight", ID: "A000"},
	}
}

func TestTheObjectDeclarationsDeclareEveryCategoryKeysSortedWithRawcodes(t *testing.T) {
	declarations := editor.RenderObjects(resolved())
	if !strings.HasPrefix(declarations, "---@meta generated.objects\n---@diagnostic disable: missing-fields\n") {
		t.Errorf("RenderObjects =\n%s", declarations)
	}
	contains(t, declarations,
		"---@class generated.objects.units\n---@field archer integer h001\n---@field captain integer h000\n",
		"---@class generated.objects.heroes\n\n",
		"---@type generated.objects.abilities\nobjects.abilities = {}\n",
		"return objects\n")
	if got := strings.Count(declarations, "---@class "); got != len(objects.Categories) {
		t.Errorf("%d classes for %d categories", got, len(objects.Categories))
	}
}

func TestTheMapDeclarationsDeclareTheMapsGlobalsAndFunctions(t *testing.T) {
	globals := &luasrc.MapGlobals{Globals: []luasrc.Global{{Name: "udg_Score", Type: "integer"}}, Functions: []string{"InitGlobals"}}
	want := "---@meta\n-- GENERATED by Moonwell from maps/map.w3x/war3map.lua; do not edit.\n\n" +
		"---@type integer\nudg_Score = nil\n\nfunction InitGlobals() end\n"
	if got := editor.RenderMap(globals, "maps/map.w3x/war3map.lua"); got != want {
		t.Errorf("RenderMap =\n%s", got)
	}
}

func TestWithoutASourceMapTheMapDeclarationsSaySoAndDeclareNothing(t *testing.T) {
	want := "---@meta\n-- GENERATED by Moonwell: there is no maps/map.w3x/war3map.lua yet; save the map in World Editor.\n"
	if got := editor.RenderMap(nil, "maps/map.w3x/war3map.lua"); got != want {
		t.Errorf("RenderMap =\n%s", got)
	}
}

func inputs() editor.Inputs {
	miniature := &natives.Natives{
		GameVersion: "9.9.9",
		Types:       []natives.Type{{Name: "agent", Extends: "handle"}},
		Functions:   []natives.Function{{Name: "DoNothing", Source: "common.j", Returns: "nothing"}},
	}
	return editor.Inputs{Objects: resolved()[:1], MapFolder: "maps/map.w3x", Natives: miniature}
}

func TestRefreshWritesTheDeclarationsAndTheMacroModuleThenOnlyWhatChanged(t *testing.T) {
	root := t.TempDir()
	testkit.WriteFile(t, root, "maps/map.w3x/war3map.lua", []byte("udg_Score = 0\nfunction main()\nend\n"))
	written, err := editor.Refresh(root, inputs())
	want := []string{
		".moonwell/types/natives.d.lua",
		".moonwell/types/moonwell.d.lua",
		".moonwell/types/objects.d.lua",
		".moonwell/types/map.d.lua",
		".moonwell/yue/moonwell/macros.yue",
	}
	if err != nil || !slices.Equal(written, want) {
		t.Fatalf("Refresh = %q, %v", written, err)
	}
	if read(t, root, ".moonwell/yue/moonwell/macros.yue") != moonwell.MacrosYue || read(t, root, ".moonwell/types/moonwell.d.lua") != editor.RuntimeDeclarations {
		t.Error("the macro module or the runtime declarations differ from the embedded ones")
	}
	contains(t, read(t, root, ".moonwell/types/map.d.lua"), "udg_Score = nil")
	if written, err := editor.Refresh(root, inputs()); err != nil || len(written) != 0 {
		t.Errorf("unchanged, but Refresh = %q, %v", written, err)
	}
	testkit.WriteFile(t, root, "maps/map.w3x/war3map.lua", []byte("udg_Other = 0\n"))
	if written, err := editor.Refresh(root, inputs()); err != nil || !slices.Equal(written, []string{".moonwell/types/map.d.lua"}) {
		t.Errorf("after a change to the map, Refresh = %q, %v", written, err)
	}
}

func TestRefreshWorksWithoutASourceMapAndWithTheEmbeddedNatives(t *testing.T) {
	root := t.TempDir()
	if _, err := editor.Refresh(root, editor.Inputs{MapFolder: "maps/map.w3x"}); err != nil {
		t.Fatal(err)
	}
	contains(t, read(t, root, ".moonwell/types/map.d.lua"), "no maps/map.w3x/war3map.lua")
	contains(t, read(t, root, ".moonwell/types/natives.d.lua"), "function CreateUnit(", "---@class unit: widget\n")
}

const mapFolderHint = "map.folder must be a map World Editor saved in folder format; re-save it that way."

func TestAScriptThatIsAFolderFails(t *testing.T) {
	root := t.TempDir()
	if err := os.MkdirAll(filepath.Join(root, "maps", "map.w3x", "war3map.lua"), 0o777); err != nil {
		t.Fatal(err)
	}
	_, err := editor.Refresh(root, inputs())
	e := asError(t, err, "a folder for a script")
	if !strings.HasPrefix(e.Msg, "Reading maps/map.w3x/war3map.lua failed: ") || e.File != "maps/map.w3x/war3map.lua" || e.Hint != mapFolderHint {
		t.Errorf("error = %+v", e)
	}
}

func TestAPackedMapFileWhereTheMapFolderShouldBeIsNoSourceMapOrAnError(t *testing.T) {
	root := t.TempDir()
	testkit.WriteFile(t, root, "maps/map.w3x", []byte("a packed map, not a folder"))
	// On Windows, reading through a file reports that the path is not found, so there is no source map.
	_, err := editor.Refresh(root, inputs())
	if runtime.GOOS == "windows" && err != nil {
		t.Errorf("Refresh = %v", err)
	}
	if err != nil {
		if e := asError(t, err, "a file for the map folder"); e.File != "maps/map.w3x/war3map.lua" || e.Hint != mapFolderHint {
			t.Errorf("error = %+v", e)
		}
	}
}

func TestAMoonwellFolderThatCannotBeWrittenFails(t *testing.T) {
	root := t.TempDir()
	testkit.WriteFile(t, root, ".moonwell", []byte("a file, not a folder"))
	_, err := editor.Refresh(root, inputs())
	e := asError(t, err, "a file for .moonwell")
	if !strings.HasPrefix(e.Msg, "Writing .moonwell/types/natives.d.lua failed: ") || e.File != ".moonwell/types/natives.d.lua" ||
		e.Hint != "Moonwell's compiler and the editor read .moonwell/; make sure it is a folder you can write, then retry." {
		t.Errorf("error = %+v", e)
	}
}

var files = []moonwell.TemplateFile{
	{Path: "yueconfig.yue", Data: []byte("return {}\n")},
	{Path: ".luarc.json", Data: []byte("{}\n")},
	{Path: ".vscode/extensions.json", Data: []byte(`{"recommendations":[]}` + "\n")},
	{Path: "src/main.yue", Data: []byte("print 1\n")},
}

// templateLuarc is the embedded template's .luarc.json.
func templateLuarc(t *testing.T) *ordered.Object {
	t.Helper()
	template, err := moonwell.TemplateFiles()
	if err != nil {
		t.Fatal(err)
	}
	for _, file := range template {
		if file.Path == ".luarc.json" {
			tree, err := ordered.Decode(file.Data)
			if err != nil {
				t.Fatal(err)
			}
			return tree.(*ordered.Object)
		}
	}
	t.Fatal("the template has no .luarc.json")
	return nil
}

func listOf(t *testing.T, config *ordered.Object, key string) []string {
	t.Helper()
	value, _ := config.Get(key)
	list, ok := value.([]any)
	if !ok {
		t.Fatalf("%s is %v, not an array", key, value)
	}
	names := make([]string, len(list))
	for i, entry := range list {
		names[i], _ = entry.(string)
	}
	return names
}

func decode(t *testing.T, text string) *ordered.Object {
	t.Helper()
	tree, err := ordered.Decode([]byte(text))
	if err != nil {
		t.Fatal(err)
	}
	return tree.(*ordered.Object)
}

func TestTheTemplateShipsEveryEditorFile(t *testing.T) {
	template, err := moonwell.TemplateFiles()
	if err != nil {
		t.Fatal(err)
	}
	for _, path := range editor.Files {
		if !slices.ContainsFunc(template, func(file moonwell.TemplateFile) bool { return file.Path == path }) {
			t.Errorf("the template has no %s", path)
		}
	}
}

func TestTheTemplatesLuarcIndexesTheCompiledLuaFilesAndSuggestsEveryGameGlobal(t *testing.T) {
	config := templateLuarc(t)
	if useGitIgnore, _ := config.Get("workspace.useGitIgnore"); useGitIgnore != false {
		t.Errorf("workspace.useGitIgnore = %v", useGitIgnore)
	}
	// The library view in .moonwell/lua is what the editor should see; the copies it is made from are not workspace
	// files.
	if !slices.Contains(listOf(t, config, "workspace.ignoreDir"), ".moonwell/libraries") {
		t.Error("workspace.ignoreDir lacks .moonwell/libraries")
	}
	// The YueScript extension asks for completion at a placeholder word, so the typed prefix never narrows the list:
	// lua-language-server must be allowed to suggest every native and game global at once.
	api := natives.Load()
	names := len(api.Functions) + len(api.Globals)
	if limit, _ := config.Get("completion.maxSuggestCount"); limit == nil || limit.(float64) < float64(names) {
		t.Errorf("completion.maxSuggestCount %v < %d names", limit, names)
	}
}

func TestAddFilesAddsMissingFilesAndGitignoreLinesAndNeverOverwrites(t *testing.T) {
	root := t.TempDir()
	testkit.WriteFile(t, root, ".luarc.json", []byte("mine\n"))
	testkit.WriteFile(t, root, ".gitignore", []byte("dist/\r\n.moonwell/\r\n"))
	added, err := editor.AddFiles(root, files)
	if want := []string{"yueconfig.yue", ".vscode/extensions.json", ".gitignore (src/**/*.lua)"}; err != nil || !slices.Equal(added, want) {
		t.Fatalf("AddFiles = %q, %v", added, err)
	}
	if read(t, root, ".luarc.json") != "mine\n" || read(t, root, "yueconfig.yue") != "return {}\n" ||
		read(t, root, ".gitignore") != "dist/\r\n.moonwell/\r\nsrc/**/*.lua\n" {
		t.Errorf(".gitignore = %q", read(t, root, ".gitignore"))
	}
	if added, err := editor.AddFiles(root, files); err != nil || len(added) != 0 {
		t.Errorf("AddFiles again = %q, %v", added, err)
	}
}

func TestAddFilesCreatesGitignoreWhenThereIsNoneAndUsesTheEmbeddedTemplate(t *testing.T) {
	root := t.TempDir()
	if _, err := editor.AddFiles(root, nil); err != nil {
		t.Fatal(err)
	}
	if got := read(t, root, ".gitignore"); got != ".moonwell/\nsrc/**/*.lua\n" {
		t.Errorf(".gitignore = %q", got)
	}
	template, _ := moonwell.TemplateFiles()
	for _, file := range template {
		if slices.Contains(editor.Files, file.Path) && read(t, root, file.Path) != string(file.Data) {
			t.Errorf("%s differs from the template's", file.Path)
		}
	}
}

func TestMergeLuarcAddsTheTemplatesMissingEntries(t *testing.T) {
	root := t.TempDir()
	testkit.WriteFile(t, root, ".luarc.json", []byte(`{"runtime.path":["src/?.lua"],"workspace.library":[".moonwell/types","extra"],`+
		`"workspace.ignoreDir":["dist","maps"],"diagnostics.globals":["X"]}`))
	added, merged, err := editor.MergeLuarc(root, nil)
	want := []string{"src/?/init.lua", "lua/?.lua", "lua/?/init.lua", ".moonwell/lua", ".moonwell/libraries"}
	if err != nil || !merged || !slices.Equal(added, want) {
		t.Fatalf("MergeLuarc = %q, %v, %v", added, merged, err)
	}
	written := `{
  "runtime.path": [
    "src/?.lua",
    "src/?/init.lua",
    "lua/?.lua",
    "lua/?/init.lua"
  ],
  "workspace.library": [
    ".moonwell/types",
    "extra",
    ".moonwell/lua"
  ],
  "workspace.ignoreDir": [
    "dist",
    "maps",
    ".moonwell/libraries"
  ],
  "diagnostics.globals": [
    "X"
  ]
}
`
	if got := read(t, root, ".luarc.json"); got != written {
		t.Errorf(".luarc.json =\n%s", got)
	}
	if added, merged, err := editor.MergeLuarc(root, nil); err != nil || !merged || len(added) != 0 {
		t.Errorf("MergeLuarc again = %q, %v, %v", added, merged, err)
	}
}

func TestLuarcTemplateEntriesListsTheTemplatesArrays(t *testing.T) {
	entries, err := editor.LuarcTemplateEntries(nil)
	want := map[string][]string{
		"runtime.path":        {"src/?.lua", "src/?/init.lua", "lua/?.lua", "lua/?/init.lua"},
		"workspace.library":   {".moonwell/types", ".moonwell/lua"},
		"workspace.ignoreDir": {"dist", "maps", ".moonwell/libraries"},
	}
	if err != nil || !reflect.DeepEqual(entries, want) {
		t.Errorf("LuarcTemplateEntries = %v, %v", entries, err)
	}
}

func TestMergeLuarcLeavesAFileThatIsNotAJSONObjectAlone(t *testing.T) {
	for _, content := range []string{"// a comment\n{ \"runtime.path\": [] }\n", "[]", "null", "3"} {
		root := t.TempDir()
		testkit.WriteFile(t, root, ".luarc.json", []byte(content))
		if added, merged, err := editor.MergeLuarc(root, nil); err != nil || merged || added != nil || read(t, root, ".luarc.json") != content {
			t.Errorf("%q: MergeLuarc = %q, %v, %v", content, added, merged, err)
		}
	}
	// No file: nothing to merge.
	if added, merged, err := editor.MergeLuarc(t.TempDir(), nil); err != nil || !merged || len(added) != 0 {
		t.Errorf("MergeLuarc without a file = %q, %v, %v", added, merged, err)
	}
}

func TestMergeLuarcGivesAMissingKeyTheTemplatesWholeArrayAndLeavesANonArrayValueAlone(t *testing.T) {
	root := t.TempDir()
	testkit.WriteFile(t, root, ".luarc.json", []byte(`{"workspace.library":"not an array"}`))
	template := templateLuarc(t)
	added, _, err := editor.MergeLuarc(root, nil)
	want := append(listOf(t, template, "runtime.path"), listOf(t, template, "workspace.ignoreDir")...)
	if err != nil || !slices.Equal(added, want) {
		t.Fatalf("MergeLuarc = %q, %v", added, err)
	}
	config := decode(t, read(t, root, ".luarc.json"))
	if library, _ := config.Get("workspace.library"); library != "not an array" ||
		!slices.Equal(listOf(t, config, "runtime.path"), listOf(t, template, "runtime.path")) ||
		!slices.Equal(config.Keys(), []string{"workspace.library", "runtime.path", "workspace.ignoreDir"}) {
		t.Errorf(".luarc.json =\n%s", read(t, root, ".luarc.json"))
	}
}

func TestMergeLuarcMergesAFileSavedWithABOM(t *testing.T) {
	root := t.TempDir()
	template := templateLuarc(t)
	testkit.WriteFile(t, root, ".luarc.json", []byte("\xEF\xBB\xBF"+`{"runtime.path":`+ordered.Stringify(mustGet(template, "runtime.path"), 0)+`}`))
	added, _, err := editor.MergeLuarc(root, nil)
	want := append(listOf(t, template, "workspace.library"), listOf(t, template, "workspace.ignoreDir")...)
	if err != nil || !slices.Equal(added, want) {
		t.Fatalf("MergeLuarc = %q, %v", added, err)
	}
	config := decode(t, read(t, root, ".luarc.json"))
	if !slices.Equal(listOf(t, config, "workspace.library"), listOf(t, template, "workspace.library")) {
		t.Errorf(".luarc.json =\n%s", read(t, root, ".luarc.json"))
	}
}

func mustGet(config *ordered.Object, key string) any {
	value, _ := config.Get(key)
	return value
}

func TestMergeLuarcReportsAFileItCannotRead(t *testing.T) {
	root := t.TempDir()
	if err := os.Mkdir(filepath.Join(root, ".luarc.json"), 0o777); err != nil {
		t.Fatal(err)
	}
	_, _, err := editor.MergeLuarc(root, nil)
	e := asError(t, err, "a folder for .luarc.json")
	if !strings.HasPrefix(e.Msg, "Reading .luarc.json failed: ") || e.File != ".luarc.json" || e.Hint == "" {
		t.Errorf("error = %+v", e)
	}
}

func libraryModules() []bundle.SourceModule {
	return []bundle.SourceModule{
		{Name: "main", Path: "src/main.yue", Kind: bundle.Yue},
		{Name: "tools", Path: "lua/tools.lua", Kind: bundle.Lua, Source: "return {}"},
		{Name: "example.greet", Path: ".moonwell/libraries/ex/example/greet.lua", Kind: bundle.Lua, Source: "return 1", Library: "ex"},
		{Name: "example.loud", Path: ".moonwell/libraries/ex/example/loud.yue", Kind: bundle.Yue, Library: "ex"},
		{Name: "kit.init", Path: ".moonwell/libraries/ex/kit/init.lua", Kind: bundle.Lua, Source: "return 2", Library: "ex"},
	}
}

func loud(module bundle.SourceModule) (*bundle.CompiledModule, error) {
	if module.Name == "example.loud" {
		return &bundle.CompiledModule{Name: module.Name, SourcePath: module.Path, Source: "return 3"}, nil
	}
	return nil, nil
}

func TestRefreshLibraryViewWritesLibraryModulesAsLuaByModulePathThenOnlyChanges(t *testing.T) {
	root := t.TempDir()
	modules := libraryModules()
	written, err := editor.RefreshLibraryView(root, modules, loud)
	want := []string{".moonwell/lua/example/greet.lua", ".moonwell/lua/example/loud.lua", ".moonwell/lua/kit/init.lua"}
	if err != nil || !slices.Equal(written, want) {
		t.Fatalf("RefreshLibraryView = %q, %v", written, err)
	}
	if read(t, root, ".moonwell/lua/example/loud.lua") != "return 3" || fsx.Exists(filepath.Join(root, ".moonwell", "lua", "tools.lua")) {
		t.Error("a project module was copied, or the compiled module was not")
	}
	if written, err := editor.RefreshLibraryView(root, modules, loud); err != nil || len(written) != 0 {
		t.Errorf("unchanged, but RefreshLibraryView = %q, %v", written, err)
	}
	none := func(bundle.SourceModule) (*bundle.CompiledModule, error) { return nil, nil }
	if written, err := editor.RefreshLibraryView(root, modules[:3], none); err != nil || len(written) != 0 {
		t.Errorf("RefreshLibraryView = %q, %v", written, err)
	}
	if fsx.Exists(filepath.Join(root, ".moonwell", "lua", "kit", "init.lua")) {
		t.Error("a module that is gone kept its view")
	}
	if _, err := editor.RefreshLibraryView(root, modules, none); err != nil || fsx.Exists(filepath.Join(root, ".moonwell", "lua", "example", "loud.lua")) {
		t.Errorf("no compiled Lua, but the view is there (%v)", err)
	}
}

func TestRefreshLibraryViewReportsACompiledOutputItCannotRead(t *testing.T) {
	busy := func(bundle.SourceModule) (*bundle.CompiledModule, error) {
		return nil, errors.New("EBUSY: resource busy or locked")
	}
	_, err := editor.RefreshLibraryView(t.TempDir(), libraryModules()[3:4], busy)
	e := asError(t, err, "a busy output")
	if e.Msg != "Writing .moonwell/lua failed: EBUSY: resource busy or locked" || e.File != ".moonwell/lua" ||
		e.Hint != "The editor reads .moonwell/; make sure it is a folder you can write, then retry." {
		t.Errorf("error = %+v", e)
	}
	expected := &diag.Error{Msg: "already a user's error"}
	_, err = editor.RefreshLibraryView(t.TempDir(), libraryModules()[3:4], func(bundle.SourceModule) (*bundle.CompiledModule, error) {
		return nil, expected
	})
	if err != expected {
		t.Errorf("error = %v", err)
	}
}

func TestRefreshLibraryViewWithoutALoaderKeepsTheViewsOfYueScriptLibraryModules(t *testing.T) {
	root := t.TempDir()
	modules := libraryModules()
	loudModule, greet := modules[3], modules[2]
	view := filepath.Join(root, ".moonwell", "lua", "example", "loud.lua")
	if _, err := editor.RefreshLibraryView(root, []bundle.SourceModule{loudModule, greet}, loud); err != nil {
		t.Fatal(err)
	}
	// Setup, after a check: it compiles nothing.
	written, err := editor.RefreshLibraryView(root, []bundle.SourceModule{loudModule, greet}, nil)
	if data, _ := os.ReadFile(view); err != nil || len(written) != 0 || string(data) != "return 3" {
		t.Errorf("RefreshLibraryView = %q, %v; the view holds %q", written, err, data)
	}
	if _, err := editor.RefreshLibraryView(root, []bundle.SourceModule{greet}, nil); err != nil || fsx.Exists(view) {
		t.Errorf("a module that went away kept its view (%v)", err)
	}
}
