package objects

import (
	"fmt"
	"path/filepath"
	"slices"
	"strings"

	"github.com/mdlsvensson/moonwell/internal/diag"
	"github.com/mdlsvensson/moonwell/internal/fsx"
	"github.com/mdlsvensson/moonwell/internal/manifest"
	"github.com/mdlsvensson/moonwell/internal/war3/objmod"
)

const IDsFile = "src/generated/objects.yue"

const idsHeader = "-- GENERATED by Moonwell from objects/**.pkl; do not edit."

func PackID(id string) (uint32, error) {
	raw, ok := objmod.ParseID(id)
	if !ok {
		return 0, fmt.Errorf("Cannot pack %s: a rawcode is 4 Latin-1 characters.", fsx.QuoteJSON(id))
	}
	return uint32(raw[0])<<24 | uint32(raw[1])<<16 | uint32(raw[2])<<8 | uint32(raw[3]), nil
}

func RenderIDs(resolved []Resolved) (string, error) {
	lines := []string{idsHeader}
	for _, category := range manifest.Categories {
		table, err := renderIDsTable(category, resolved)
		if err != nil {
			return "", err
		}
		lines = append(lines, table...)
	}
	return strings.Join(lines, "\n") + "\n", nil
}

func renderIDsTable(category manifest.Category, resolved []Resolved) ([]string, error) {
	var entries []Resolved
	for _, object := range resolved {
		if object.Category == category {
			entries = append(entries, object)
		}
	}
	if len(entries) == 0 {
		return []string{"export " + string(category) + " = {}"}, nil
	}
	slices.SortStableFunc(entries, func(a, b Resolved) int { return strings.Compare(a.Key, b.Key) })
	lines := []string{"export " + string(category) + " = {"}
	for _, entry := range entries {
		packed, err := PackID(entry.ID)
		if err != nil {
			return nil, err
		}
		lines = append(lines, fmt.Sprintf("  %s: %d -- %s", entry.Key, packed, entry.ID))
	}
	return append(lines, "}"), nil
}

var noIDs, _ = RenderIDs(nil)

type IDsStatus string

const (
	IDsCurrent IDsStatus = "current"
	IDsStale   IDsStatus = "stale"
	IDsMissing IDsStatus = "missing"
)

func CheckIDsStatus(root, expected string) (IDsStatus, error) {
	data, found, err := fsx.ReadFileIfExists(idsPath(root))
	switch {
	case err != nil:
		return "", errIDsUnreadable(err)
	case !found && expected == noIDs:
		return IDsCurrent, nil
	case !found:
		return IDsMissing, nil
	}
	if strings.ReplaceAll(string(data), "\r\n", "\n") == expected {
		return IDsCurrent, nil
	}
	return IDsStale, nil
}

func RefreshIDs(root, expected string) (wrote bool, err error) {
	status, err := CheckIDsStatus(root, expected)
	if err != nil || status == IDsCurrent {
		return false, err
	}
	if wrote, err = fsx.WriteIfChanged(idsPath(root), expected); err != nil {
		return false, errIDsUnwritable(err)
	}
	return wrote, nil
}

func RequireIDsCurrent(root, expected string) error {
	status, err := CheckIDsStatus(root, expected)
	switch {
	case err != nil || status == IDsCurrent:
		return err
	case status == IDsMissing:
		return errIDsMissing()
	}
	return errIDsStale()
}

func idsPath(root string) string {
	return filepath.Join(root, filepath.FromSlash(IDsFile))
}

const regenerateIDs = "Run moonwell build, test or dev to regenerate it."

func errIDsUnreadable(cause error) error {
	return &diag.Error{
		Msg:   "Reading the generated object ids failed: " + fsx.Reason(cause),
		File:  IDsFile,
		Hint:  "Make sure this is a readable file, not a folder.",
		Cause: cause,
	}
}

func errIDsUnwritable(cause error) error {
	return &diag.Error{
		Msg:   "Writing the generated object ids failed: " + fsx.Reason(cause),
		File:  IDsFile,
		Hint:  "Make sure src/generated is a folder this user may write to, and that no other program has the file open.",
		Cause: cause,
	}
}

func errIDsMissing() error {
	return &diag.Error{Msg: "The file is missing, but the manifest has objects.", File: IDsFile, Hint: regenerateIDs}
}

func errIDsStale() error {
	return &diag.Error{Msg: "The file does not match the objects in the manifest.", File: IDsFile, Hint: regenerateIDs}
}
