package objects

import (
	"errors"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"slices"
	"strings"

	"github.com/mdlsvensson/moonwell/internal/diag"
	"github.com/mdlsvensson/moonwell/internal/fsx"
	"github.com/mdlsvensson/moonwell/internal/layout"
	"github.com/mdlsvensson/moonwell/internal/text"
)

const (
	idsHeader  = "-- GENERATED by Moonwell from objects/**.pkl; do not edit."
	regenerate = "Run moonwell build, test or dev to regenerate it."
)

// PackID returns a rawcode as the game's integer id: its four bytes big-endian, as FourCC and
// string.unpack(">I4", id) give it.
func PackID(id string) (uint32, error) {
	raw, ok := fromLatin1(id)
	if !ok {
		return 0, fmt.Errorf("Cannot pack %s: a rawcode is 4 Latin-1 characters.", text.Quote(id))
	}
	return uint32(raw[0])<<24 | uint32(raw[1])<<16 | uint32(raw[2])<<8 | uint32(raw[3]), nil
}

// RenderIDs renders src/generated/objects.yue for objects: every category in order, keys sorted, rawcodes
// commented. Only Category, Key and ID are read.
func RenderIDs(objects []Resolved) string {
	lines := []string{idsHeader}
	for _, category := range Categories {
		var entries []Resolved
		for _, object := range objects {
			if object.Category == category {
				entries = append(entries, object)
			}
		}
		if len(entries) == 0 {
			lines = append(lines, "export "+string(category)+" = {}")
			continue
		}
		slices.SortStableFunc(entries, func(a, b Resolved) int { return text.Compare(a.Key, b.Key) })
		lines = append(lines, "export "+string(category)+" = {")
		for _, entry := range entries {
			packed, err := PackID(entry.ID)
			if err != nil {
				panic(err) // the resolver accepts only ids of four ASCII letters or digits
			}
			lines = append(lines, fmt.Sprintf("  %s: %d -- %s", entry.Key, packed, entry.ID))
		}
		lines = append(lines, "}")
	}
	return strings.Join(lines, "\n") + "\n"
}

// WriteIDs writes the generated module under root unless it already has exactly content. It reports whether it
// wrote.
func WriteIDs(root, content string) (bool, error) {
	return fsx.WriteIfChanged(filepath.Join(root, filepath.FromSlash(layout.ObjectIDsFile)), content)
}

// IDsStatus says how the generated module under a project compares with what the manifest produces.
type IDsStatus string

const (
	IDsCurrent IDsStatus = "current"
	IDsStale   IDsStatus = "stale"
	IDsMissing IDsStatus = "missing"
)

// StatusOfIDs reports whether the generated module under root is what the manifest produces (expected). A missing
// file is current when the manifest has no objects, so projects from before objects keep passing check.
func StatusOfIDs(root, expected string) (IDsStatus, error) {
	data, err := os.ReadFile(filepath.Join(root, filepath.FromSlash(layout.ObjectIDsFile)))
	if errors.Is(err, fs.ErrNotExist) {
		if expected == RenderIDs(nil) {
			return IDsCurrent, nil
		}
		return IDsMissing, nil
	}
	if err != nil {
		return "", &diag.Error{
			Msg:   "Reading the generated object ids failed: " + fsx.Reason(err),
			File:  layout.ObjectIDsFile,
			Cause: err,
			Hint:  "Make sure this is a readable file, not a folder.",
		}
	}
	// A Windows checkout with core.autocrlf has CRLF line endings; the module is the same.
	if strings.ReplaceAll(text.Lossy(data), "\r\n", "\n") == expected {
		return IDsCurrent, nil
	}
	return IDsStale, nil
}

// RefreshIDs brings the generated module under root up to date with expected (build, test and dev). It writes
// nothing when the module is current, so a project without objects gets no file and a CRLF checkout is not
// rewritten. It reports whether it wrote.
func RefreshIDs(root, expected string) (bool, error) {
	status, err := StatusOfIDs(root, expected)
	if err != nil || status == IDsCurrent {
		return false, err
	}
	return WriteIDs(root, expected)
}

// AssertIDsCurrent is check's staleness rule: it fails when the generated module is stale, or missing while there
// are objects.
func AssertIDsCurrent(root, expected string) error {
	status, err := StatusOfIDs(root, expected)
	if err != nil || status == IDsCurrent {
		return err
	}
	message := "The file does not match the objects in the manifest."
	if status == IDsMissing {
		message = "The file is missing, but the manifest has objects."
	}
	return &diag.Error{Msg: message, File: layout.ObjectIDsFile, Hint: regenerate}
}
