package objects_test

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/mdlsvensson/moonwell/internal/objects"
)

var emptyIDs = strings.Join([]string{
	"-- GENERATED by Moonwell from objects/**.pkl; do not edit.",
	"export heroes = {}",
	"export units = {}",
	"export buildings = {}",
	"export items = {}",
	"export abilities = {}",
	"export buffs = {}",
	"export upgrades = {}",
	"",
}, "\n")

func object(category objects.Category, key, id string) objects.Resolved {
	return objects.Resolved{Category: category, Key: key, ID: id}
}

var captainIDs = objects.RenderIDs([]objects.Resolved{object("units", "captain", "h000")})

func idsFile(root string) string { return filepath.Join(root, "src", "generated", "objects.yue") }

func status(t *testing.T, root, expected string) objects.IDsStatus {
	t.Helper()
	got, err := objects.StatusOfIDs(root, expected)
	if err != nil {
		t.Fatal(err)
	}
	return got
}

func write(t *testing.T, root, content string) bool {
	t.Helper()
	wrote, err := objects.WriteIDs(root, content)
	if err != nil {
		t.Fatal(err)
	}
	return wrote
}

func TestPackIDPacksARawcodeBigEndian(t *testing.T) {
	for id, want := range map[string]uint32{
		"h000": 1747988528, "A000": 0x41303030,
		// Unsigned: ids starting with a byte of 0x80 or more stay positive.
		"ÿ\x00\x00\x00": 0xff000000,
	} {
		if got, err := objects.PackID(id); err != nil || got != want {
			t.Errorf("PackID(%q) = %d, %v", id, got, err)
		}
	}
	if _, err := objects.PackID("h00"); err == nil {
		t.Error("PackID accepted three characters")
	}
}

func TestRenderIDsWritesEveryCategoryInOrderEvenWhenEmpty(t *testing.T) {
	if got := objects.RenderIDs(nil); got != emptyIDs {
		t.Errorf("RenderIDs = %q", got)
	}
}

func TestRenderIDsSortsKeysWithinEachCategoryAndCommentsEachRawcode(t *testing.T) {
	got := objects.RenderIDs([]objects.Resolved{
		object("units", "captain", "h000"),
		object("abilities", "holy", "A001"),
		object("units", "Archer", "h002"),
		object("heroes", "paladin", "H000"),
		object("units", "archer", "h001"),
		object("upgrades", "swords", "R000"),
	})
	want := strings.Join([]string{
		"-- GENERATED by Moonwell from objects/**.pkl; do not edit.",
		"export heroes = {",
		"  paladin: 1211117616 -- H000",
		"}",
		"export units = {",
		"  Archer: 1747988530 -- h002",
		"  archer: 1747988529 -- h001",
		"  captain: 1747988528 -- h000",
		"}",
		"export buildings = {}",
		"export items = {}",
		"export abilities = {",
		"  holy: 1093677105 -- A001",
		"}",
		"export buffs = {}",
		"export upgrades = {",
		"  swords: 1378889776 -- R000",
		"}",
		"",
	}, "\n")
	if got != want {
		t.Errorf("RenderIDs =\n%s", got)
	}
}

func TestStatusOfIDsIsCurrentStaleOrMissingWhileTheManifestHasObjects(t *testing.T) {
	root := t.TempDir()
	// No objects and no file passes, so projects from before objects keep passing check.
	if got := status(t, root, emptyIDs); got != objects.IDsCurrent {
		t.Errorf("no file, no objects: %s", got)
	}
	if got := status(t, root, captainIDs); got != objects.IDsMissing {
		t.Errorf("no file, with objects: %s", got)
	}
	if !write(t, root, captainIDs) {
		t.Error("the first write wrote nothing")
	}
	if data, _ := os.ReadFile(idsFile(root)); string(data) != captainIDs {
		t.Errorf("the file holds %q", data)
	}
	if write(t, root, captainIDs) {
		t.Error("an unchanged module was written again")
	}
	if got := status(t, root, captainIDs); got != objects.IDsCurrent {
		t.Errorf("a written module: %s", got)
	}
	if got := status(t, root, emptyIDs); got != objects.IDsStale {
		t.Errorf("a module for other objects: %s", got)
	}
	write(t, root, emptyIDs)
	if got := status(t, root, emptyIDs); got != objects.IDsCurrent {
		t.Errorf("an empty module: %s", got)
	}
}

func TestAssertIDsCurrentFailsOnAStaleOrMissingFileWithTheRegenerateHint(t *testing.T) {
	root := t.TempDir()
	if err := objects.AssertIDsCurrent(root, emptyIDs); err != nil {
		t.Error(err)
	}
	const hint = "Run moonwell build, test or dev to regenerate it."
	missing := asError(t, objects.AssertIDsCurrent(root, captainIDs), "a missing module")
	if missing.Msg != "The file is missing, but the manifest has objects." || missing.File != "src/generated/objects.yue" || missing.Hint != hint {
		t.Errorf("error = %+v", missing)
	}
	write(t, root, emptyIDs)
	stale := asError(t, objects.AssertIDsCurrent(root, captainIDs), "a stale module")
	if stale.Msg != "The file does not match the objects in the manifest." || stale.File != "src/generated/objects.yue" || stale.Hint != hint {
		t.Errorf("error = %+v", stale)
	}
	write(t, root, captainIDs)
	if err := objects.AssertIDsCurrent(root, captainIDs); err != nil {
		t.Error(err)
	}
}

func TestStatusOfIDsReadsACRLFCheckoutAsTheSameModule(t *testing.T) {
	root := t.TempDir()
	write(t, root, strings.ReplaceAll(captainIDs, "\n", "\r\n"))
	if got := status(t, root, captainIDs); got != objects.IDsCurrent {
		t.Errorf("a CRLF checkout: %s", got)
	}
	if err := objects.AssertIDsCurrent(root, captainIDs); err != nil {
		t.Error(err)
	}
	// A lone CR is a real difference.
	os.WriteFile(idsFile(root), []byte(strings.ReplaceAll(captainIDs, "\n", "\r")), 0o666)
	if got := status(t, root, captainIDs); got != objects.IDsStale {
		t.Errorf("lone CRs: %s", got)
	}
	// A folder in the module's place is a file error.
	other := t.TempDir()
	os.MkdirAll(idsFile(other), 0o777)
	_, err := objects.StatusOfIDs(other, captainIDs)
	if e := asError(t, err, "a folder"); e.File != "src/generated/objects.yue" || !strings.HasPrefix(e.Msg, "Reading the generated object ids failed: ") {
		t.Errorf("error = %+v", e)
	}
}

func TestRefreshIDsWritesOnlyAStaleOrMissingModuleNeverAnUnneededEmptyOne(t *testing.T) {
	root := t.TempDir()
	refresh := func(expected string) bool {
		t.Helper()
		wrote, err := objects.RefreshIDs(root, expected)
		if err != nil {
			t.Fatal(err)
		}
		return wrote
	}
	if refresh(emptyIDs) {
		t.Error("no objects wrote a module")
	}
	if _, err := os.Stat(idsFile(root)); err == nil {
		t.Error("no objects created a file")
	}
	if !refresh(captainIDs) {
		t.Error("a missing module was not written")
	}
	if data, _ := os.ReadFile(idsFile(root)); string(data) != captainIDs {
		t.Errorf("the file holds %q", data)
	}
	os.WriteFile(idsFile(root), []byte(strings.ReplaceAll(captainIDs, "\n", "\r\n")), 0o666)
	if refresh(captainIDs) {
		t.Error("a CRLF checkout was rewritten")
	}
	if !refresh(emptyIDs) {
		t.Error("removing every object did not empty the module")
	}
	if data, _ := os.ReadFile(idsFile(root)); string(data) != emptyIDs {
		t.Errorf("the file holds %q", data)
	}
}
