package objects_test

import (
	"errors"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/mdlsvensson/moonwell/internal/diag"
	"github.com/mdlsvensson/moonwell/internal/manifest"
	"github.com/mdlsvensson/moonwell/internal/objects"
	"github.com/mdlsvensson/moonwell/internal/testkit"
)

var emptyIDs = strings.Join([]string{
	"-- GENERATED by Moonwell from objects/**.pkl; do not edit.",
	"export heroes = {}",
	"export units = {}",
	"export buildings = {}",
	"export items = {}",
	"export abilities = {}",
	"export buffs = {}",
	"export upgrades = {}",
	"",
}, "\n")

func object(category manifest.Category, key, id string) objects.Resolved {
	return objects.Resolved{Category: category, Key: key, ID: id}
}

var captainIDs, _ = objects.RenderIDs([]objects.Resolved{object("units", "captain", "h000")})

func mustRenderIDs(t *testing.T, resolved []objects.Resolved) string {
	t.Helper()
	ids, err := objects.RenderIDs(resolved)
	if err != nil {
		t.Fatal(err)
	}
	return ids
}

func idsFile(root string) string { return filepath.Join(root, "src", "generated", "objects.yue") }

func mustIDsStatus(t *testing.T, root, expected string) objects.IDsStatus {
	t.Helper()
	got, err := objects.CheckIDsStatus(root, expected)
	if err != nil {
		t.Fatal(err)
	}
	return got
}

func mustRefreshIDs(t *testing.T, root, expected string) bool {
	t.Helper()
	wrote, err := objects.RefreshIDs(root, expected)
	if err != nil {
		t.Fatal(err)
	}
	return wrote
}

func asDiagError(t *testing.T, err error, what string) *diag.Error {
	t.Helper()
	var diagErr *diag.Error
	if !errors.As(err, &diagErr) {
		t.Fatalf("%s: got %v, want a *diag.Error", what, err)
	}
	return diagErr
}

func TestPackIDPacksARawcodeBigEndian(t *testing.T) {
	for id, want := range map[string]uint32{
		"h000": 1747988528, "A000": 0x41303030,
		"\xc3\xbf\x00\x00\x00": 0xff000000,
	} {
		if got, err := objects.PackID(id); err != nil || got != want {
			t.Errorf("PackID(%q) = %d, %v", id, got, err)
		}
	}
	for _, id := range []string{"h00", "h0000", "", "h00\xe2\x82\xac"} {
		_, err := objects.PackID(id)
		var expected *diag.Error
		if err == nil || errors.As(err, &expected) || !strings.Contains(err.Error(), "4 Latin-1 characters") {
			t.Errorf("PackID(%q) = %v, want a plain error", id, err)
		}
	}
}

func TestRenderIDsWritesEveryCategoryInOrderEvenWhenEmpty(t *testing.T) {
	if got, err := objects.RenderIDs(nil); err != nil || got != emptyIDs {
		t.Errorf("RenderIDs = %q, %v", got, err)
	}
	if objects.IDsFile != "src/generated/objects.yue" {
		t.Errorf("IDsFile = %q", objects.IDsFile)
	}
}

func TestRenderIDsGivesAPlainErrorForAnIDThatDoesNotPack(t *testing.T) {
	short := []objects.Resolved{object("units", "captain", "h000"), object("units", "archer", "h00")}
	got, err := objects.RenderIDs(short)
	var expected *diag.Error
	if got != "" || err == nil || errors.As(err, &expected) || !strings.Contains(err.Error(), `"h00"`) {
		t.Errorf("RenderIDs = %q, %v, want a plain error that names the id", got, err)
	}
}

func TestRenderIDsSortsKeysWithinEachCategoryAndCommentsEachRawcode(t *testing.T) {
	got, err := objects.RenderIDs([]objects.Resolved{
		object("units", "captain", "h000"),
		object("abilities", "holy", "A001"),
		object("units", "Archer", "h002"),
		object("heroes", "paladin", "H000"),
		object("units", "archer", "h001"),
		object("upgrades", "swords", "R000"),
	})
	want := strings.Join([]string{
		"-- GENERATED by Moonwell from objects/**.pkl; do not edit.",
		"export heroes = {",
		"  paladin: 1211117616 -- H000",
		"}",
		"export units = {",
		"  Archer: 1747988530 -- h002",
		"  archer: 1747988529 -- h001",
		"  captain: 1747988528 -- h000",
		"}",
		"export buildings = {}",
		"export items = {}",
		"export abilities = {",
		"  holy: 1093677105 -- A001",
		"}",
		"export buffs = {}",
		"export upgrades = {",
		"  swords: 1378889776 -- R000",
		"}",
		"",
	}, "\n")
	if err != nil || got != want {
		t.Errorf("RenderIDs = %v\n%s", err, got)
	}
}

func TestStatusOfIDsIsCurrentStaleOrMissing(t *testing.T) {
	root := t.TempDir()
	if got := mustIDsStatus(t, root, emptyIDs); got != objects.IDsCurrent {
		t.Errorf("no file, no objects: %s", got)
	}
	if got := mustIDsStatus(t, root, captainIDs); got != objects.IDsMissing {
		t.Errorf("no file, with objects: %s", got)
	}
	testkit.WriteFile(t, root, objects.IDsFile, []byte(captainIDs))
	if got := mustIDsStatus(t, root, captainIDs); got != objects.IDsCurrent {
		t.Errorf("the module of these objects: %s", got)
	}
	if got := mustIDsStatus(t, root, emptyIDs); got != objects.IDsStale {
		t.Errorf("the module of other objects: %s", got)
	}
	testkit.WriteFile(t, root, objects.IDsFile, []byte(emptyIDs))
	if got := mustIDsStatus(t, root, emptyIDs); got != objects.IDsCurrent {
		t.Errorf("an empty module: %s", got)
	}
}

func TestAssertIDsCurrentFailsOnAStaleOrMissingFileWithTheHintToRegenerate(t *testing.T) {
	root := t.TempDir()
	if err := objects.RequireIDsCurrent(root, emptyIDs); err != nil {
		t.Error(err)
	}
	const hint = "Run moonwell build, test or dev to regenerate it."
	missing := asDiagError(t, objects.RequireIDsCurrent(root, captainIDs), "a missing module")
	if !strings.Contains(missing.Msg, "is missing, but the project has objects") || missing.File != objects.IDsFile || missing.Hint != hint {
		t.Errorf("error = %+v", missing)
	}
	testkit.WriteFile(t, root, objects.IDsFile, []byte(emptyIDs))
	stale := asDiagError(t, objects.RequireIDsCurrent(root, captainIDs), "a stale module")
	if !strings.Contains(stale.Msg, "does not match the project's objects") || stale.File != objects.IDsFile || stale.Hint != hint {
		t.Errorf("error = %+v", stale)
	}
	testkit.WriteFile(t, root, objects.IDsFile, []byte(captainIDs))
	if err := objects.RequireIDsCurrent(root, captainIDs); err != nil {
		t.Error(err)
	}
}

func TestStatusOfIDsReadsACheckoutWithCRLFLineEndingsAsTheSameModule(t *testing.T) {
	root := t.TempDir()
	testkit.WriteFile(t, root, objects.IDsFile, []byte(strings.ReplaceAll(captainIDs, "\n", "\r\n")))
	if got := mustIDsStatus(t, root, captainIDs); got != objects.IDsCurrent {
		t.Errorf("CRLF line endings: %s", got)
	}
	if err := objects.RequireIDsCurrent(root, captainIDs); err != nil {
		t.Error(err)
	}
	for name, content := range map[string]string{
		"CR alone":          strings.ReplaceAll(captainIDs, "\n", "\r"),
		"a byte order mark": "\xEF\xBB\xBF" + captainIDs,
	} {
		testkit.WriteFile(t, root, objects.IDsFile, []byte(content))
		if got := mustIDsStatus(t, root, captainIDs); got != objects.IDsStale {
			t.Errorf("%s: %s", name, got)
		}
	}
	other := t.TempDir()
	if err := os.MkdirAll(idsFile(other), 0o777); err != nil {
		t.Fatal(err)
	}
	for name, err := range map[string]error{
		"StatusOfIDs":      errOf(objects.CheckIDsStatus(other, captainIDs)),
		"RefreshIDs":       errOf(objects.RefreshIDs(other, captainIDs)),
		"AssertIDsCurrent": objects.RequireIDsCurrent(other, captainIDs),
	} {
		diagErr := asDiagError(t, err, name)
		if diagErr.File != objects.IDsFile || !strings.HasPrefix(diagErr.Msg, "Reading the generated object ids failed: ") ||
			diagErr.Hint == "" || diagErr.Cause == nil {
			t.Errorf("%s: error = %+v", name, diagErr)
		}
	}
}

func errOf[T any](_ T, err error) error { return err }

func TestRefreshIDsWritesOnlyAStaleOrMissingModuleAndNeverAnEmptyOneThatIsNotNeeded(t *testing.T) {
	root := t.TempDir()
	if mustRefreshIDs(t, root, emptyIDs) {
		t.Error("no objects wrote a module")
	}
	if _, err := os.Stat(idsFile(root)); err == nil {
		t.Error("no objects created a file")
	}
	if !mustRefreshIDs(t, root, captainIDs) {
		t.Error("a missing module was not written")
	}
	if data, _ := os.ReadFile(idsFile(root)); string(data) != captainIDs {
		t.Errorf("the file holds %q", data)
	}
	if mustRefreshIDs(t, root, captainIDs) {
		t.Error("a current module was written again")
	}
	testkit.WriteFile(t, root, objects.IDsFile, []byte(strings.ReplaceAll(captainIDs, "\n", "\r\n")))
	if mustRefreshIDs(t, root, captainIDs) {
		t.Error("a checkout with CRLF line endings was rewritten")
	}
	if !mustRefreshIDs(t, root, emptyIDs) {
		t.Error("removing every object did not empty the module")
	}
	if data, _ := os.ReadFile(idsFile(root)); string(data) != emptyIDs {
		t.Errorf("the file holds %q", data)
	}
}

func TestRefreshIDsNamesTheModuleWhenItCannotBeWritten(t *testing.T) {
	root := t.TempDir()
	testkit.WriteFile(t, root, "src/generated", []byte("a file"))
	wrote, err := objects.RefreshIDs(root, captainIDs)
	diagErr := asDiagError(t, err, "a file in place of the folder")
	if wrote || diagErr.File != objects.IDsFile || !strings.Contains(diagErr.Msg, "the generated object ids failed: ") ||
		diagErr.Hint == "" || diagErr.Cause == nil {
		t.Errorf("RefreshIDs = %v, %+v", wrote, diagErr)
	}
}
