// GENERATED by `deno task gen` — do not edit.
/** cli/data/game-paths.txt, gzip-compressed. */
export const GAME_PATHS_GZIP_BASE64: string = "H4sIAAAAAAAA/1NW8MsvUUhPzUstSixJTVGoTC2xUigqzVNISEnNy1coSSzOBslapSfmpuoWJJZkFCvY5GQWl6Rl5qTaKdiAhBXKUouKM/Pz7BIUNIpTUxWc/f1CgjydQkM8/dz1clM09bgADJLxdGUAAAA=";
