import { join } from "@std/path";
import { writeTextIfChanged } from "../shared/fs.ts";
import { MoonwellError } from "../shared/errors.ts";
import { CATEGORIES } from "./metadata.ts";
import type { ResolvedObject } from "./resolve.ts";

/** The generated module, relative to the project root. */
export const OBJECT_IDS_FILE = "src/generated/objects.yue";

const HEADER = "-- GENERATED by Moonwell from objects/**.pkl; do not edit.";
const REGENERATE = "Run deno task build, test or dev to regenerate it.";

/** A rawcode as the game's integer id: its four bytes big-endian, as `FourCC` and `string.unpack(">I4", id)`. */
export function packId(id: string): number {
  const codes = Array.from(id, (c) => c.charCodeAt(0));
  if (codes.length !== 4 || codes.some((code) => code > 0xff)) {
    throw new Error(`Cannot pack ${JSON.stringify(id)}: a rawcode is 4 Latin-1 characters.`);
  }
  return codes.reduce((packed, code) => packed * 256 + code, 0);
}

/** `src/generated/objects.yue` for `objects` (spec §8): every category in order, keys sorted, rawcodes commented. */
export function renderObjectIds(objects: Pick<ResolvedObject, "category" | "key" | "id">[]): string {
  const lines = [HEADER];
  for (const category of CATEGORIES) {
    const entries = objects
      .filter((object) => object.category === category)
      .sort((a, b) => a.key < b.key ? -1 : a.key > b.key ? 1 : 0);
    if (entries.length === 0) {
      lines.push(`export ${category} = {}`);
      continue;
    }
    lines.push(`export ${category} = {`);
    for (const { key, id } of entries) lines.push(`  ${key}: ${packId(id)} -- ${id}`);
    lines.push("}");
  }
  return `${lines.join("\n")}\n`;
}

/** Writes the generated module under `root` unless it already has exactly `text`. Returns whether it wrote. */
export function writeObjectIds(root: string, text: string): Promise<boolean> {
  return writeTextIfChanged(join(root, OBJECT_IDS_FILE), text);
}

/**
 * Whether the generated module under `root` is what the manifest produces (`expected`). A missing file is current
 * when the manifest has no objects, so projects from before objects keep passing `check`.
 */
export async function objectIdsStatus(root: string, expected: string): Promise<"current" | "stale" | "missing"> {
  let current: string;
  try {
    current = await Deno.readTextFile(join(root, OBJECT_IDS_FILE));
  } catch (cause) {
    if (!(cause instanceof Deno.errors.NotFound)) {
      const reason = cause instanceof Error ? cause.message : String(cause);
      throw new MoonwellError(`Reading the generated object ids failed: ${reason}`, {
        file: OBJECT_IDS_FILE,
        cause,
        hint: "Make sure this is a readable file, not a folder.",
      });
    }
    return expected === renderObjectIds([]) ? "current" : "missing";
  }
  // A Windows checkout with core.autocrlf has CRLF line endings; the module is the same.
  return current.replaceAll("\r\n", "\n") === expected ? "current" : "stale";
}

/**
 * Brings the generated module under `root` up to date with `expected` (build, test and dev, spec §8). Writes nothing
 * when it is current, so a project without objects gets no file and a CRLF checkout is not rewritten.
 * Returns whether it wrote.
 */
export async function refreshObjectIds(root: string, expected: string): Promise<boolean> {
  if ((await objectIdsStatus(root, expected)) === "current") return false;
  return await writeObjectIds(root, expected);
}

/** `check`'s staleness rule (spec §8): fails when the generated module is stale, or missing while there are objects. */
export async function assertObjectIdsCurrent(root: string, expected: string): Promise<void> {
  const status = await objectIdsStatus(root, expected);
  if (status === "current") return;
  throw new MoonwellError(
    status === "missing"
      ? "The file is missing, but the manifest has objects."
      : "The file does not match the objects in the manifest.",
    { file: OBJECT_IDS_FILE, hint: REGENERATE },
  );
}
