/** Renders cli/src/embedded/*: JSR modules cannot read their own non-TS files when run remotely. */
import { encodeBase64 } from "@std/encoding/base64";
import { dirname, fromFileUrl, join } from "@std/path";
import { listFiles, writeTextIfChanged } from "../cli/src/shared/fs.ts";
import { TEMPLATE_EXCLUDE } from "../cli/src/project-files.ts";
import { gzip } from "../cli/src/shared/compression.ts";

export const REPO = join(dirname(fromFileUrl(import.meta.url)), "..");
const HEADER = "// GENERATED by `deno task gen` — do not edit.\n";

export async function renderEmbedded(repo: string = REPO): Promise<Map<string, string>> {
  const out = new Map<string, string>();
  const runtime = await Deno.readTextFile(join(repo, "cli", "runtime", "moonwell.lua"));
  out.set("cli/src/embedded/runtime.ts", `${HEADER}export const RUNTIME_LUA: string = ${JSON.stringify(runtime)};\n`);

  const entries = (await templateEntries(repo)).map((file) =>
    `  { path: ${JSON.stringify(file.path)}, base64: ${JSON.stringify(file.base64)} },`
  );
  out.set(
    "cli/src/embedded/template.ts",
    `${HEADER}export const TEMPLATE_FILES: ReadonlyArray<{ path: string; base64: string }> = [\n${
      entries.join("\n")
    }\n];\n`,
  );

  const gamePaths = await Deno.readFile(join(repo, "cli", "data", "game-paths.txt"));
  out.set(
    "cli/src/embedded/game-paths.ts",
    `${HEADER}/** cli/data/game-paths.txt, gzip-compressed. */\nexport const GAME_PATHS_GZIP_BASE64: string = ${
      JSON.stringify(encodeBase64(await gzip(gamePaths)))
    };\n`,
  );
  return out;
}

/** Every file init copies from template/, in listing order, as base64. */
export async function templateEntries(repo: string = REPO): Promise<Array<{ path: string; base64: string }>> {
  const templateDir = join(repo, "template");
  const excluded = new Set<string>(TEMPLATE_EXCLUDE);
  const entries: Array<{ path: string; base64: string }> = [];
  for (const path of await listFiles(templateDir)) {
    if (excluded.has(path) || path.startsWith("dist/")) continue;
    entries.push({ path, base64: encodeBase64(await Deno.readFile(join(templateDir, ...path.split("/")))) });
  }
  return entries;
}

if (import.meta.main) {
  for (const [path, text] of await renderEmbedded()) {
    if (await writeTextIfChanged(join(REPO, ...path.split("/")), text)) console.log(`wrote ${path}`);
  }
}
