/** Renders cli/src/embedded/*: JSR modules cannot read their own non-TS files when run remotely. */
import { encodeBase64 } from "@std/encoding/base64";
import { dirname, fromFileUrl, join } from "@std/path";
import { listFiles, writeTextIfChanged } from "../cli/src/shared/fs.ts";
import { TEMPLATE_EXCLUDE } from "../cli/src/project-files.ts";
import { gzip } from "../cli/src/shared/compression.ts";
import type { Metadata } from "../cli/src/objectdata/metadata.ts";
import { renderSchema } from "./schema.ts";

export const REPO = join(dirname(fromFileUrl(import.meta.url)), "..");
const HEADER = "// GENERATED by `deno task gen` — do not edit.\n";

export async function renderEmbedded(repo: string = REPO): Promise<Map<string, string>> {
  const out = new Map<string, string>();
  const runtime = await Deno.readTextFile(join(repo, "cli", "runtime", "moonwell.lua"));
  out.set("cli/src/embedded/runtime.ts", `${HEADER}export const RUNTIME_LUA: string = ${JSON.stringify(runtime)};\n`);

  const entries = (await templateEntries(repo)).map((file) =>
    `  { path: ${JSON.stringify(file.path)}, base64: ${JSON.stringify(file.base64)} },`
  );
  out.set(
    "cli/src/embedded/template.ts",
    `${HEADER}export const TEMPLATE_FILES: ReadonlyArray<{ path: string; base64: string }> = [\n${
      entries.join("\n")
    }\n];\n`,
  );

  const gamePaths = await Deno.readFile(join(repo, "cli", "data", "game-paths.txt"));
  out.set(
    "cli/src/embedded/game-paths.ts",
    `${HEADER}/** cli/data/game-paths.txt, gzip-compressed. */\nexport const GAME_PATHS_GZIP_BASE64: string = ${
      JSON.stringify(encodeBase64(await gzip(gamePaths)))
    };\n`,
  );

  const metadata = await Deno.readFile(join(repo, "cli", "data", "metadata.json"));
  out.set(
    "cli/src/embedded/metadata.ts",
    `${HEADER}/** cli/data/metadata.json, gzip-compressed. */\nexport const METADATA_GZIP_BASE64: string = ${
      JSON.stringify(encodeBase64(await gzip(metadata)))
    };\n`,
  );

  const natives = await Deno.readFile(join(repo, "cli", "data", "natives.json"));
  out.set(
    "cli/src/embedded/natives.ts",
    `${HEADER}/** cli/data/natives.json, gzip-compressed. */\nexport const NATIVES_GZIP_BASE64: string = ${
      JSON.stringify(encodeBase64(await gzip(natives)))
    };\n`,
  );
  return out;
}

/** schema/generated/*.pkl, rendered from cli/data/metadata.json; the folder holds nothing else. */
export async function renderGeneratedSchema(repo: string = REPO): Promise<Map<string, string>> {
  const metadata = JSON.parse(await Deno.readTextFile(join(repo, "cli", "data", "metadata.json"))) as Metadata;
  return renderSchema(metadata);
}

/**
 * What builds, `check`/`setup` and the YueScript extension write inside a project, git-ignored there: never part of
 * the template, even when those commands have run in template/.
 */
function isGenerated(path: string): boolean {
  return path.startsWith("dist/") || path.startsWith(".moonwell/") ||
    (path.startsWith("src/") && path.endsWith(".lua"));
}

/** Every file init copies from template/, in listing order, as base64. */
export async function templateEntries(repo: string = REPO): Promise<Array<{ path: string; base64: string }>> {
  const templateDir = join(repo, "template");
  const excluded = new Set<string>(TEMPLATE_EXCLUDE);
  const entries: Array<{ path: string; base64: string }> = [];
  for (const path of await listFiles(templateDir)) {
    if (excluded.has(path) || isGenerated(path)) continue;
    entries.push({ path, base64: encodeBase64(await Deno.readFile(join(templateDir, ...path.split("/")))) });
  }
  return entries;
}

if (import.meta.main) {
  const schema = await renderGeneratedSchema();
  for (const [path, text] of [...await renderEmbedded(), ...schema]) {
    if (await writeTextIfChanged(join(REPO, ...path.split("/")), text)) console.log(`wrote ${path}`);
  }
  const generated = join(REPO, "schema", "generated");
  for await (const entry of Deno.readDir(generated)) {
    if (schema.has(`schema/generated/${entry.name}`)) continue;
    await Deno.remove(join(generated, entry.name), { recursive: true });
    console.log(`removed schema/generated/${entry.name}`);
  }
}
