/** Renders cli/src/embedded/*: JSR modules cannot read their own non-TS files when run remotely. */
import { encodeBase64 } from "@std/encoding/base64";
import { dirname, fromFileUrl, join } from "@std/path";
import { listFiles, writeTextIfChanged } from "../cli/src/shared/fs.ts";
import { TEMPLATE_EXCLUDE } from "../cli/src/project-files.ts";

export const REPO = join(dirname(fromFileUrl(import.meta.url)), "..");
const HEADER = "// GENERATED by `deno task gen` — do not edit.\n";

export async function renderEmbedded(repo: string = REPO): Promise<Map<string, string>> {
  const out = new Map<string, string>();
  const runtime = await Deno.readTextFile(join(repo, "cli", "runtime", "moonwell.lua"));
  out.set("cli/src/embedded/runtime.ts", `${HEADER}export const RUNTIME_LUA: string = ${JSON.stringify(runtime)};\n`);

  const templateDir = join(repo, "template");
  const excluded = new Set<string>(TEMPLATE_EXCLUDE);
  const entries: string[] = [];
  for (const path of await listFiles(templateDir)) {
    if (excluded.has(path) || path.startsWith("dist/")) continue;
    const bytes = await Deno.readFile(join(templateDir, ...path.split("/")));
    entries.push(`  { path: ${JSON.stringify(path)}, base64: ${JSON.stringify(encodeBase64(bytes))} },`);
  }
  out.set(
    "cli/src/embedded/template.ts",
    `${HEADER}export const TEMPLATE_FILES: ReadonlyArray<{ path: string; base64: string }> = [\n${
      entries.join("\n")
    }\n];\n`,
  );
  return out;
}

if (import.meta.main) {
  for (const [path, text] of await renderEmbedded()) {
    if (await writeTextIfChanged(join(REPO, ...path.split("/")), text)) console.log(`wrote ${path}`);
  }
}
