/** Renders schema/generated/*Props.pkl from the object metadata (spec §4.2). */
import { type Category, FIELD_SOURCE, type FieldMeta, type Metadata } from "../cli/src/objectdata/metadata.ts";

/** Each object category's Pkl module name, as in `schema/objects/<Name>.pkl`. */
const MODULES: Record<Category, string> = {
  heroes: "Hero",
  units: "Unit",
  buildings: "Building",
  items: "Item",
  abilities: "Ability",
  buffs: "Buff",
  upgrades: "Upgrade",
};

// Names an object module already has: `Object.pkl`'s properties, the category's `id`, and Pkl's module `output`.
const RESERVED = new Set(["id", "base", "source", "properties", "output"]);
// Pkl 0.32 keywords and words reserved for future use.
const PKL_KEYWORDS = new Set(
  ("abstract amends as case class const delete else extends external false fixed for function hidden if import in is " +
    "let local module new nothing null open out outer override private protected public read record super switch " +
    "this throw trace true typealias unknown vararg when").split(" "),
);

/** The fields that get a typed property in a category's module: ability-specific fields go through `properties`. */
export function typedFields(metadata: Metadata, category: Category): FieldMeta[] {
  const source = FIELD_SOURCE[category];
  return metadata.fields[source.fields].filter((field) =>
    (source.use === undefined || field.use.includes(source.use)) && field.specific.length === 0
  );
}

/** A rawcode as authors see it: `Crs` is padded with NUL to four bytes in the metadata. */
export const displayRawcode = (id: string) => id.replace(/\0+$/, "");

/** Maps `schema/generated/<Name>Props.pkl` to its text. Throws on a name no Pkl property can have or two fields share. */
export function renderSchema(metadata: Metadata): Map<string, string> {
  const out = new Map<string, string>();
  const problems: string[] = [];
  for (const category of Object.keys(MODULES) as Category[]) {
    const module = `${MODULES[category]}Props`;
    const fields = typedFields(metadata, category).sort((a, b) => compare(a.name, b.name) || compare(a.id, b.id));
    const seen = new Map<string, FieldMeta>();
    for (const field of fields) {
      const where = `${module}: field ${JSON.stringify(displayRawcode(field.id))} (${field.label})`;
      if (!/^[A-Za-z_][A-Za-z0-9_]*$/.test(field.name) || RESERVED.has(field.name) || PKL_KEYWORDS.has(field.name)) {
        problems.push(
          `${where} has the name ${JSON.stringify(field.name)}, which is reserved or not a Pkl identifier.`,
        );
      }
      const other = seen.get(field.name);
      if (other !== undefined) {
        problems.push(
          `${where} has the name ${JSON.stringify(field.name)}, as does field ${
            JSON.stringify(displayRawcode(other.id))
          }.`,
        );
      }
      seen.set(field.name, field);
    }
    out.set(`schema/generated/${module}.pkl`, renderModule(metadata, category, module, fields));
  }
  if (problems.length > 0) {
    throw new Error(
      `Cannot render the Pkl schema; fix the names in tools/metadata/overrides.json:\n${problems.join("\n")}`,
    );
  }
  return out;
}

function renderModule(metadata: Metadata, category: Category, module: string, fields: FieldMeta[]): string {
  const lines = [
    `// GENERATED by \`deno task gen\` from cli/data/metadata.json (game ${metadata.game}) — do not edit.`,
    "",
    `/// The typed properties of \`${MODULES[category]}.pkl\`: ${
      category === "abilities" ? "the ability fields not specific to one base ability" : `the fields of ${category}`
    }, named after their World Editor labels.`,
    `abstract module moonwell.generated.${module}`,
    "",
    'extends "../objects/Object.pkl"',
  ];
  for (const field of fields) {
    lines.push("", `/// ${oneLine(field.label)}`, "///", `/// ${facts(field)}`, `${field.name}: ${pklType(field)}`);
  }
  return lines.join("\n") + "\n";
}

function facts(field: FieldMeta): string {
  const parts = [`Field \`${displayRawcode(field.id)}\` (${oneLine(field.category)}, \`${field.type}\`).`];
  if (field.perLevel) parts.push("Per level: a `List` sets levels 1, 2, ...");
  if (field.list) parts.push("A comma-separated list: a `List<String>` is joined with commas.");
  if (field.skin) parts.push("Skin field.");
  return parts.join(" ");
}

function pklType(field: FieldMeta): string {
  if (field.list) return field.perLevel ? "(String|List<String>|List<List<String>>)?" : "(String|List<String>)?";
  const scalar = field.storage === "string"
    ? "String"
    : field.storage === "int"
    ? (field.type === "bool" ? "Boolean" : "Int")
    : "Number";
  return field.perLevel ? `(${scalar}|List<${scalar}>)?` : `${scalar}?`;
}

const oneLine = (text: string) => text.replace(/\s+/g, " ").trim();
const compare = (a: string, b: string) => a < b ? -1 : a > b ? 1 : 0;
