package objects

import (
	"errors"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"slices"
	"strings"

	"github.com/mdlsvensson/moonwell/next/internal/diag"
	"github.com/mdlsvensson/moonwell/next/internal/fsx"
	"github.com/mdlsvensson/moonwell/next/internal/manifest"
	"github.com/mdlsvensson/moonwell/next/internal/war3/objmod"
)

// IDsFile is the generated module, from the project folder.
const IDsFile = "src/generated/objects.yue"

const idsHeader = "-- GENERATED by Moonwell from objects/**.pkl; do not edit."

// PackID returns a rawcode as the number the game knows it by: its four bytes, the first the highest, as FourCC
// and string.unpack(">I4", id) give it. An id that is not four bytes is a bug in the caller.
func PackID(id string) (uint32, error) {
	raw, ok := objmod.ParseID(id)
	if !ok {
		return 0, fmt.Errorf("Cannot pack %s: a rawcode is 4 Latin-1 characters.", fsx.Quoted(id))
	}
	return uint32(raw[0])<<24 | uint32(raw[1])<<16 | uint32(raw[2])<<8 | uint32(raw[3]), nil
}

// RenderIDs renders the generated module for the objects: a table for every category in order, with the objects
// sorted by key, each as its number and, in a comment, its rawcode. It reads only the category, the key and the
// id of an object.
func RenderIDs(resolved []Resolved) string {
	lines := []string{idsHeader}
	for _, category := range manifest.Categories {
		lines = append(lines, idsTable(category, resolved)...)
	}
	return strings.Join(lines, "\n") + "\n"
}

// idsTable is the lines of one category's table.
func idsTable(category manifest.Category, resolved []Resolved) []string {
	var entries []Resolved
	for _, object := range resolved {
		if object.Category == category {
			entries = append(entries, object)
		}
	}
	if len(entries) == 0 {
		return []string{"export " + string(category) + " = {}"}
	}
	slices.SortStableFunc(entries, func(a, b Resolved) int { return strings.Compare(a.Key, b.Key) })
	lines := []string{"export " + string(category) + " = {"}
	for _, entry := range entries {
		packed, err := PackID(entry.ID)
		if err != nil {
			panic(err) // Resolve lets through only ids of four letters or digits
		}
		lines = append(lines, fmt.Sprintf("  %s: %d -- %s", entry.Key, packed, entry.ID))
	}
	return append(lines, "}")
}

// IDsStatus says how the generated module of a project compares with what its manifest renders.
type IDsStatus string

const (
	IDsCurrent IDsStatus = "current"
	IDsStale   IDsStatus = "stale"
	IDsMissing IDsStatus = "missing"
)

// StatusOfIDs reports whether the generated module under root is what the manifest renders (expected). A module
// that is not there is current when the manifest has no objects, so a project that never had any needs no file.
func StatusOfIDs(root, expected string) (IDsStatus, error) {
	data, err := os.ReadFile(idsPath(root))
	switch {
	case errors.Is(err, fs.ErrNotExist) && expected == RenderIDs(nil):
		return IDsCurrent, nil
	case errors.Is(err, fs.ErrNotExist):
		return IDsMissing, nil
	case err != nil:
		return "", errIDsUnreadable(err)
	}
	// A checkout on Windows may have CRLF line endings; the module is the same.
	if strings.ReplaceAll(string(data), "\r\n", "\n") == expected {
		return IDsCurrent, nil
	}
	return IDsStale, nil
}

// RefreshIDs brings the generated module under root up to date with expected, and reports whether it wrote. It
// writes nothing when the module is current, so a project without objects gets no file and a checkout with CRLF
// line endings is not rewritten.
func RefreshIDs(root, expected string) (wrote bool, err error) {
	status, err := StatusOfIDs(root, expected)
	if err != nil || status == IDsCurrent {
		return false, err
	}
	if wrote, err = fsx.WriteIfChanged(idsPath(root), expected); err != nil {
		return false, errIDsUnwritable(err)
	}
	return wrote, nil
}

// AssertIDsCurrent fails when the generated module under root is stale, or missing while the manifest has
// objects.
func AssertIDsCurrent(root, expected string) error {
	status, err := StatusOfIDs(root, expected)
	switch {
	case err != nil || status == IDsCurrent:
		return err
	case status == IDsMissing:
		return errIDsMissing()
	}
	return errIDsStale()
}

// idsPath is where the generated module of the project in root is.
func idsPath(root string) string {
	return filepath.Join(root, filepath.FromSlash(IDsFile))
}

// ---- errors ----

const regenerateIDs = "Run moonwell build, test or dev to regenerate it."

func errIDsUnreadable(cause error) error {
	return &diag.Error{
		Msg:   "Reading the generated object ids failed: " + fsx.Reason(cause),
		File:  IDsFile,
		Hint:  "Make sure this is a readable file, not a folder.",
		Cause: cause,
	}
}

func errIDsUnwritable(cause error) error {
	return &diag.Error{
		Msg:   "Writing the generated object ids failed: " + fsx.Reason(cause),
		File:  IDsFile,
		Hint:  "Make sure src/generated is a folder this user may write to, and that no other program has the file open.",
		Cause: cause,
	}
}

func errIDsMissing() error {
	return &diag.Error{Msg: "The file is missing, but the manifest has objects.", File: IDsFile, Hint: regenerateIDs}
}

func errIDsStale() error {
	return &diag.Error{Msg: "The file does not match the objects in the manifest.", File: IDsFile, Hint: regenerateIDs}
}
