import type { Natives } from "../natives/natives.ts";
import { CATEGORIES } from "../objectdata/metadata.ts";
import type { ResolvedObject } from "../objectdata/resolve.ts";

const LUA_TYPES: Record<string, string> = {
  integer: "integer",
  real: "number",
  boolean: "boolean",
  string: "string",
  code: "function",
};

const LUA_KEYWORDS = new Set([
  "and",
  "break",
  "do",
  "else",
  "elseif",
  "end",
  "false",
  "for",
  "function",
  "goto",
  "if",
  "in",
  "local",
  "nil",
  "not",
  "or",
  "repeat",
  "return",
  "then",
  "true",
  "until",
  "while",
]);

/** The LuaLS type for a JASS type (spec §3.4). Handle types, and Lua types from the Lua extras, pass through. */
export function luaType(jassType: string): string {
  return LUA_TYPES[jassType] ?? jassType;
}

/** A JASS parameter name as a Lua identifier: Lua keywords get a trailing underscore. */
function paramName(name: string): string {
  return LUA_KEYWORDS.has(name) ? `${name}_` : name;
}

/** Handle classes, each after its parent, starting from `handle` (declared by no `type` line). */
function classLines(natives: Natives): string[] {
  const children = new Map<string, string[]>();
  for (const type of natives.types) children.set(type.extends, [...(children.get(type.extends) ?? []), type.name]);
  const lines = ["---@class handle"];
  const visit = (parent: string) => {
    for (const name of (children.get(parent) ?? []).sort()) {
      lines.push(`---@class ${name}: ${parent}`);
      visit(name);
    }
  };
  visit("handle");
  return lines;
}

/** .moonwell/types/natives.d.lua (spec §4.2). */
export function renderNativesDeclarations(natives: Natives): string {
  const out = [
    "---@meta",
    `-- GENERATED by Moonwell from Warcraft III ${natives.gameVersion} (common.j, blizzard.j); do not edit.`,
    "",
    ...classLines(natives),
    "",
  ];
  for (const fn of natives.functions) {
    for (const param of fn.params) out.push(`---@param ${paramName(param.name)} ${luaType(param.type)}`);
    if (fn.returns !== "nothing") out.push(`---@return ${luaType(fn.returns)}`);
    out.push(`function ${fn.name}(${fn.params.map((param) => paramName(param.name)).join(", ")}) end`, "");
  }
  for (const global of natives.globals) {
    out.push(`---@type ${luaType(global.type)}${global.array ? "[]" : ""}`, `${global.name} = nil`, "");
  }
  return out.join("\n");
}

/** .moonwell/types/moonwell.d.lua: the runtime module (`cli/runtime/moonwell.lua`) as gameplay code sees it. */
export const RUNTIME_DECLARATIONS = [
  "---@meta moonwell",
  "-- GENERATED by Moonwell; do not edit.",
  "",
  "---The Moonwell runtime. Hooks of one kind run in the order they were added. A failing hook prints its error",
  "---with the .yue file and line, and the other hooks still run.",
  "local moonwell = {}",
  "",
  "---Adds `fn` to run when the game calls config(), before World Editor's config() sets up players, forces and",
  "---start locations.",
  "---@param fn fun()",
  "function moonwell.before_config(fn) end",
  "",
  "---Adds `fn` to run when the game calls config(), after World Editor's config() has set up players and forces.",
  "---@param fn fun()",
  "function moonwell.on_config(fn) end",
  "",
  "---Adds `fn` to run when the game calls main(), before World Editor's main() creates preplaced units and runs",
  "---the initialization triggers.",
  "---@param fn fun()",
  "function moonwell.before_main(fn) end",
  "",
  "---Adds `fn` to run when the game calls main(), after World Editor's main(): preplaced units exist and the",
  "---initialization triggers have run.",
  "---@param fn fun()",
  "function moonwell.on_main(fn) end",
  "",
  "---Rewrites war3map.lua line numbers in an error message to src/*.yue files and lines (only the file in",
  "---minified builds).",
  "---@param message string",
  "---@return string",
  "function moonwell.format_error(message) end",
  "",
  "return moonwell",
  "",
].join("\n");

/** .moonwell/types/objects.d.lua: `src/generated/objects.yue` as gameplay code sees it (spec §4.2). */
export function renderObjectDeclarations(objects: Pick<ResolvedObject, "category" | "key" | "id">[]): string {
  const out = [
    "---@meta generated.objects",
    // `objects.units = {}` below would otherwise warn that the class's fields are missing.
    "---@diagnostic disable: missing-fields",
    "-- GENERATED by Moonwell from objects/**.pkl; do not edit.",
    "",
  ];
  for (const category of CATEGORIES) {
    out.push(`---@class generated.objects.${category}`);
    const entries = objects.filter((object) => object.category === category)
      .sort((a, b) => a.key < b.key ? -1 : a.key > b.key ? 1 : 0);
    for (const { key, id } of entries) out.push(`---@field ${key} integer ${id}`);
    out.push("");
  }
  out.push("local objects = {}", "");
  for (const category of CATEGORIES) {
    out.push(`---@type generated.objects.${category}`, `objects.${category} = {}`, "");
  }
  out.push("return objects", "");
  return out.join("\n");
}
