export interface MapGlobals {
  /** Variables World Editor declares at the top of war3map.lua, in file order. `type` is a LuaLS type or "any". */
  globals: Array<{ name: string; type: string }>;
  /** Every top-level `function Name(` in the file, in file order. */
  functions: string[];
}

const HANDLE_PREFIXES: Record<string, string> = {
  unit: "unit",
  trg: "trigger",
  rct: "rect",
  cam: "camerasetup",
  snd: "sound",
  dest: "destructable",
  item: "item",
};

function valueType(value: string): string {
  if (/^-?\d+$/.test(value)) return "integer";
  if (/^-?\d*\.\d+$/.test(value)) return "number";
  if (/^"/.test(value)) return "string";
  if (value === "true" || value === "false") return "boolean";
  const array = /^__jarray\((.*)\)$/.exec(value);
  if (array) return `${valueType(array[1].trim())}[]`;
  if (value === "{}") return "any[]";
  return "any";
}

/** World Editor's globals (the `name = value` lines before the first function) and functions (spec §4.2). */
export function readMapGlobals(script: string): MapGlobals {
  const result: MapGlobals = { globals: [], functions: [] };
  let inDeclarations = true;
  for (const line of script.split(/\r?\n/)) {
    const fn = /^function\s+([A-Za-z_]\w*)\s*\(/.exec(line);
    if (fn) {
      inDeclarations = false;
      result.functions.push(fn[1]);
      continue;
    }
    if (!inDeclarations) continue;
    const declaration = /^([A-Za-z_]\w*)\s*=\s*(.*?)\s*$/.exec(line);
    if (!declaration) continue;
    const [, name, value] = declaration;
    const handle = /^gg_([a-z]+)_/.exec(name);
    const type = handle ? HANDLE_PREFIXES[handle[1]] ?? "any" : valueType(value);
    result.globals.push({ name, type });
  }
  return result;
}

/** .moonwell/types/map.d.lua; `source` is the war3map.lua it came from, as the project names it. */
export function renderMapDeclarations(globals: MapGlobals | undefined, source: string): string {
  if (globals === undefined) {
    return ["---@meta", `-- GENERATED by Moonwell: there is no ${source} yet; save the map in World Editor.`, ""]
      .join("\n");
  }
  const out = ["---@meta", `-- GENERATED by Moonwell from ${source}; do not edit.`, ""];
  for (const global of globals.globals) out.push(`---@type ${global.type}`, `${global.name} = nil`, "");
  for (const fn of globals.functions) out.push(`function ${fn}() end`, "");
  return out.join("\n");
}
