// Package conformance compares the two command lines while the TypeScript implementation still exists. It is
// test-only and is removed in Plan 5e; no fixture or oracle is generated by either implementation under test.
package conformance

import (
	"bytes"
	"context"
	"crypto/sha256"
	"encoding/binary"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"slices"
	"strings"
	"testing"
	"time"

	"github.com/mdlsvensson/moonwell/internal/cli"
	"github.com/mdlsvensson/moonwell/internal/mpq"
	"github.com/mdlsvensson/moonwell/internal/testkit"
	"github.com/mdlsvensson/moonwell/internal/yuetest"
)

type outcome struct {
	code     int
	out, err string
}

type harness struct {
	repo, deno, compiler string
}

type pair struct{ deno, goCLI string }

func TestConformance(t *testing.T) {
	if os.Getenv("MOONWELL_CONFORMANCE") != "1" {
		t.Skip("set MOONWELL_CONFORMANCE=1 to compare Go and Deno")
	}
	h := harness{repo: testkit.RepoRoot(t)}
	var err error
	h.deno, err = exec.LookPath("deno")
	if err != nil {
		if os.Getenv("MOONWELL_REQUIRE_TOOLS") == "1" {
			t.Fatal("conformance requires deno on PATH")
		}
		t.Skip("conformance requires deno on PATH")
	}
	if _, err := os.Stat(filepath.Join(h.repo, "cli/src/main.ts")); err != nil {
		t.Fatal("conformance requires the TypeScript CLI: ", err)
	}
	testkit.NeedPkl(t)
	h.compiler = yuetest.Need(t)

	// The initialized template is the seed for independent scenarios. Each scenario has two equally deep copies;
	// their relative Pkl dependency points at the same checkout, and no build/cache/output crosses between them.
	seed := h.initPair(t)
	t.Run("template", func(t *testing.T) {
		p := clonePair(t, seed)
		h.pinCompiler(t, p)
		for _, args := range [][]string{{"setup"}, {"check"}, {"build"}, {"build", "--minify"}, {"objects:eval"}, {"objects:check"}, {"settings:check"}, {"assets:check"}, {"assets:paths"}} {
			h.compare(t, p, 0, args...)
		}
	})
	t.Run("gate-local-libraries", func(t *testing.T) {
		gate := filepath.Join(filepath.Dir(h.repo), "wrappers-gate")
		if _, err := os.Stat(filepath.Join(gate, "moonwell.pkl")); os.IsNotExist(err) {
			t.Skip("optional ../wrappers-gate is absent")
		}
		p := clonePair(t, seed)
		for _, root := range []string{p.deno, p.goCLI} {
			copyTree(t, gate, root, func(name string) bool {
				first := strings.Split(name, "/")[0]
				return !slices.Contains([]string{".git", ".moonwell", ".asset-state", "dist", "deno.json", "deno.lock", "PklProject", "PklProject.deps.json", "moonwell.local.pkl"}, first)
			})
			local := "libraries {\n"
			for _, lib := range []string{"wrappers", "systems"} {
				path := filepath.ToSlash(filepath.Join(filepath.Dir(h.repo), "moonwell-"+lib))
				if _, err := os.Stat(path); err != nil {
					t.Fatal("gate library: ", err)
				}
				local += fmt.Sprintf("  [%q] { path = %q; dir = \"src\" }\n", lib, path)
			}
			h.local(t, root, local+"}\n")
		}
		for _, args := range [][]string{{"check"}, {"build"}, {"build", "--minify"}} {
			h.compare(t, p, 0, args...)
		}
	})
	t.Run("every-setting", func(t *testing.T) {
		p := clonePair(t, seed)
		for _, root := range []string{p.deno, p.goCLI} {
			settingsMap(t, root)
			h.local(t, root, everySetting)
		}
		h.compare(t, p, 0, "settings:check")
		h.compare(t, p, 0, "build")
	})
	t.Run("every-object-category", func(t *testing.T) {
		p := clonePair(t, seed)
		for _, root := range []string{p.deno, p.goCLI} {
			copyTree(t, filepath.Join(h.repo, "cli/tests/fixtures/objects-v3-names"), filepath.Join(root, "maps/map.w3x"), func(name string) bool { return strings.HasPrefix(name, "war3map") })
			// Existing World Editor objects remain untouched; new IDs cannot collide with its h000/I000/etc.
			if err := os.RemoveAll(filepath.Join(root, "objects")); err != nil {
				t.Fatal(err)
			}
			testkit.WriteFile(t, root, "objects/all.pkl", []byte(everyObject))
			h.local(t, root, "")
		}
		// Deliberately stale first: both commands must report it without silently rewriting the generated source.
		h.compareDiagnostic(t, p, "does not match the objects in the manifest", "objects:check")
		h.compare(t, p, 0, "objects:eval")
		h.compare(t, p, 0, "build")
		h.compare(t, p, 0, "objects:check")
	})
	t.Run("imports-and-assets-sync", func(t *testing.T) {
		p := clonePair(t, seed)
		for _, root := range []string{p.deno, p.goCLI} {
			testkit.WriteFile(t, root, "maps/map.w3x/war3map.imp", testkit.Fixture(t, "imports-we3/war3map-flag29.imp"))
			testkit.WriteFile(t, root, "assets/icons/icon.blp", []byte{1, 2, 3, 0, 255})
			testkit.WriteFile(t, root, "assets/Models/unit.mdl", []byte("Version { FormatVersion 800, }\nTextures 2 { Bitmap { Image \"icons/icon.blp\", } Bitmap { Image \"Textures/white.blp\", } }\n"))
			h.local(t, root, "")
		}
		for _, args := range [][]string{{"assets:check"}, {"assets:paths"}, {"assets:sync"}, {"assets:check"}, {"build"}} {
			h.compare(t, p, 0, args...)
		}
	})
	for _, format := range []string{"tga", "blp"} {
		t.Run("preview-"+format, func(t *testing.T) {
			p := clonePair(t, seed)
			picture := testkit.BLP(256, 1)
			if format == "tga" {
				picture = testkit.TGA(testkit.NewPixels(512), testkit.TGAOptions{RLE: true, FromTop: true, ID: 9})
			}
			for _, root := range []string{p.deno, p.goCLI} {
				settingsMap(t, root)
				testkit.WriteFile(t, root, "preview."+format, picture)
				h.local(t, root, fmt.Sprintf("settings { info { preview = %q } }\n", "preview."+format))
			}
			h.compare(t, p, 0, "settings:check")
			h.compare(t, p, 0, "build")
		})
	}
	t.Run("lua-and-tagged-library", func(t *testing.T) {
		testkit.NeedNetwork(t)
		p := clonePair(t, seed)
		for _, root := range []string{p.deno, p.goCLI} {
			h.local(t, root, "libraries { [\"example\"] { github = \"mdlsvensson/moonwell-example-lib\"; tag = \"v0.2.0\" } }\n")
			testkit.WriteFile(t, root, "lua/localmod/init.lua", []byte("local M = {}\nfunction M.value() return 42 end\nreturn M\n"))
			appendFile(t, root, "src/main.yue", "\nimport \"example.loud\"\nimport \"localmod\"\nprint loud.shout \"Moonwell\"\nprint localmod.value!\n")
		}
		h.compare(t, p, 0, "check")
		h.compare(t, p, 0, "build")
	})
	for _, failure := range []string{"syntax-error", "unknown-global", "stale-objects", "missing-source-map", "wrong-package-version"} {
		t.Run(failure, func(t *testing.T) {
			p := clonePair(t, seed)
			for _, root := range []string{p.deno, p.goCLI} {
				h.local(t, root, "")
				switch failure {
				case "syntax-error":
					testkit.WriteFile(t, root, "src/main.yue", []byte("on_main = ->\n  x = (\n"))
				case "unknown-global":
					appendFile(t, root, "src/main.yue", "\nMoonwellTypoNobodyDefines!\n")
				case "stale-objects":
					testkit.WriteFile(t, root, "src/generated/objects.yue", []byte("return {}\n"))
				case "missing-source-map":
					if err := os.RemoveAll(filepath.Join(root, "maps/map.w3x")); err != nil {
						t.Fatal(err)
					}
				case "wrong-package-version":
					path := filepath.Join(root, "PklProject.deps.json")
					data, err := os.ReadFile(path)
					if err != nil {
						t.Fatal(err)
					}
					testkit.WriteFile(t, root, "PklProject.deps.json", bytes.ReplaceAll(data, []byte("@0.7.0"), []byte("@0.6.0")))
				}
			}
			command := "check"
			if failure == "missing-source-map" {
				command = "build"
			}
			diagnostic := map[string]string{
				"syntax-error":          "src/main.yue:2 › expected only one expression in parenthesis",
				"unknown-global":        "MoonwellTypoNobodyDefines",
				"stale-objects":         "does not match the objects in the manifest",
				"missing-source-map":    "Source map folder maps/map.w3x not found.",
				"wrong-package-version": "Pkl package moonwell@0.6.0 does not match Moonwell CLI 0.7.0.",
			}[failure]
			h.compareDiagnostic(t, p, diagnostic, command)
		})
	}
}

func (h harness) initPair(t *testing.T) pair {
	t.Helper()
	parent := t.TempDir()
	p := pair{filepath.Join(parent, "deno", "map"), filepath.Join(parent, "go", "map")}
	a := h.runDeno(t, h.repo, "init", "--link", p.deno)
	b := runGo(t, h.repo, "init", "--link", p.goCLI)
	compareOutcome(t, p, a, b, 0)
	compareFiles(t, p, []string{"."}, true)
	return p
}

func clonePair(t *testing.T, seed pair) pair {
	t.Helper()
	parent := t.TempDir()
	p := pair{filepath.Join(parent, "deno", "map"), filepath.Join(parent, "go", "map")}
	copyTree(t, seed.deno, p.deno, nil)
	copyTree(t, seed.goCLI, p.goCLI, nil)
	return p
}

func (h harness) pinCompiler(t *testing.T, p pair) {
	for _, root := range []string{p.deno, p.goCLI} {
		h.local(t, root, "")
	}
}

func (h harness) local(t *testing.T, root, body string) {
	t.Helper()
	testkit.WriteFile(t, root, "moonwell.local.pkl", []byte("amends \"moonwell.pkl\"\nyue { path = "+fmt.Sprintf("%q", filepath.ToSlash(h.compiler))+" }\n"+body))
}

func (h harness) compare(t *testing.T, p pair, want int, args ...string) {
	t.Helper()
	h.compareCommand(t, p, want, "", args...)
}

func (h harness) compareDiagnostic(t *testing.T, p pair, diagnostic string, args ...string) {
	t.Helper()
	h.compareCommand(t, p, 1, diagnostic, args...)
}

func (h harness) compareCommand(t *testing.T, p pair, want int, diagnostic string, args ...string) {
	t.Helper()
	t.Run(strings.Join(args, "_"), func(t *testing.T) {
		a := h.runDeno(t, p.deno, args...)
		b := runGo(t, p.goCLI, args...)
		compareOutcome(t, p, a, b, want)
		if diagnostic != "" && (!strings.Contains(a.err, diagnostic) || !strings.Contains(b.err, diagnostic)) {
			t.Errorf("expected failure diagnostic %q\nDeno:\n%s\nGo:\n%s", diagnostic, a.err, b.err)
		}
		// §6.2 lists the staged map, editor and library views, generated sources and the lock. Include the entire
		// source map/state after every command to catch accidental writes by planners as well as assets:sync.
		compareFiles(t, p, []string{
			"dist/stage/map.w3x", ".moonwell", "src/generated", "moonwell.lock", "maps", ".asset-state",
			".gitignore", ".luarc.json", ".vscode", "yueconfig.yue", "moonwell.pkl", "moonwell.local.pkl",
			"PklProject", "PklProject.deps.json",
		}, false)
		compareArchives(t, p)
	})
}

func (h harness) runDeno(t *testing.T, root string, args ...string) outcome {
	t.Helper()
	ctx, cancel := context.WithTimeout(context.Background(), 3*time.Minute)
	defer cancel()
	cmd := exec.CommandContext(ctx, h.deno, append([]string{"run", "-A", filepath.Join(h.repo, "cli/src/main.ts")}, args...)...)
	cmd.Dir = root
	var stdout, stderr bytes.Buffer
	cmd.Stdout, cmd.Stderr = &stdout, &stderr
	err := cmd.Run()
	code := 0
	if err != nil {
		if exit, ok := err.(*exec.ExitError); ok {
			code = exit.ExitCode()
		} else {
			t.Fatalf("Deno command: %v", err)
		}
	}
	if ctx.Err() != nil {
		t.Fatal("Deno command timed out: ", stderr.String())
	}
	return outcome{code, stdout.String(), stderr.String()}
}

func runGo(t *testing.T, root string, args ...string) outcome {
	t.Helper()
	ctx, cancel := context.WithTimeout(context.Background(), 3*time.Minute)
	defer cancel()
	var stdout, stderr strings.Builder
	code := cli.Run(ctx, args, root, func(line string) { stderr.WriteString(line + "\n") }, func(line string) { stdout.WriteString(line + "\n") })
	return outcome{code, stdout.String(), stderr.String()}
}

var denoTask = regexp.MustCompile(`\bdeno task ([A-Za-z][A-Za-z0-9:_-]*)`)

// Normalize only copy-specific paths and the contract's Deno text changes. Do not trim, reorder lines, discard
// warnings, rewrite path separators globally or parse/re-serialize JSON: those would hide actual differences.
func normalize(value, root string) string {
	value = strings.ReplaceAll(value, root, "<project>")
	value = strings.ReplaceAll(value, filepath.ToSlash(root), "<project>")
	value = strings.ReplaceAll(value, strings.ReplaceAll(root, `\`, `\\`), "<project>")
	value = strings.ReplaceAll(value, "file:///"+filepath.ToSlash(root), "file:///<project>")
	value = denoTask.ReplaceAllString(value, "moonwell $1")
	// §8.3 explicitly changes this version-mismatch hint because the program replaces the deno.json dependency.
	value = strings.ReplaceAll(value, "Use moonwell@0.7.x in PklProject and @moonwell/cli@0.7.x in deno.json, then run `pkl project resolve`.", "Use moonwell@0.7.x in PklProject and run `pkl project resolve`.")
	return value
}

func compareOutcome(t *testing.T, p pair, a, b outcome, want int) {
	t.Helper()
	if a.code != want || b.code != want {
		t.Errorf("exit codes: Deno=%d Go=%d expected=%d\nDeno stderr:\n%s\nGo stderr:\n%s", a.code, b.code, want, a.err, b.err)
	}
	for _, stream := range []struct{ name, a, b string }{{"stdout", a.out, b.out}, {"stderr", a.err, b.err}} {
		left, right := normalize(stream.a, p.deno), normalize(stream.b, p.goCLI)
		if left != right {
			t.Errorf("%s differs\nDeno:\n%s\nGo:\n%s", stream.name, left, right)
		}
	}
}

func compareFiles(t *testing.T, p pair, roots []string, scaffold bool) {
	t.Helper()
	a, b := collectFiles(t, p.deno, roots), collectFiles(t, p.goCLI, roots)
	if scaffold {
		delete(a, "deno.json")
	} // §2: init's only excluded generated file.
	names := make([]string, 0, len(a)+len(b))
	for name := range a {
		names = append(names, name)
	}
	for name := range b {
		names = append(names, name)
	}
	slices.Sort(names)
	names = slices.Compact(names)
	for _, name := range names {
		left, foundA := a[name]
		right, foundB := b[name]
		if !foundA || !foundB {
			t.Errorf("file set differs at %s: Deno=%v Go=%v", name, foundA, foundB)
			continue
		}
		// init's generated local comment is the one file whose bytes explicitly name the replaced command.
		if scaffold && name == "moonwell.local.pkl" {
			left = []byte(normalize(string(left), p.deno))
			right = []byte(normalize(string(right), p.goCLI))
		}
		if !bytes.Equal(left, right) {
			t.Errorf("file bytes differ at %s (Deno %d bytes sha256 %x; Go %d bytes sha256 %x)", name, len(left), sha256.Sum256(left), len(right), sha256.Sum256(right))
		}
	}
}

func collectFiles(t *testing.T, root string, selected []string) map[string][]byte {
	t.Helper()
	files := map[string][]byte{}
	for _, name := range selected {
		start := filepath.Join(root, filepath.FromSlash(name))
		if _, err := os.Stat(start); os.IsNotExist(err) {
			continue
		}
		err := filepath.WalkDir(start, func(path string, entry os.DirEntry, err error) error {
			if err != nil {
				return err
			}
			if entry.IsDir() {
				return nil
			}
			rel, err := filepath.Rel(root, path)
			if err != nil {
				return err
			}
			data, err := os.ReadFile(path)
			if err != nil {
				return err
			}
			files[filepath.ToSlash(rel)] = data
			return nil
		})
		if err != nil {
			t.Fatal(err)
		}
	}
	return files
}

func compareArchives(t *testing.T, p pair) {
	t.Helper()
	name := "dist/bin/map.w3x"
	a, errA := os.ReadFile(filepath.Join(p.deno, name))
	b, errB := os.ReadFile(filepath.Join(p.goCLI, name))
	if os.IsNotExist(errA) && os.IsNotExist(errB) {
		return
	}
	if errA != nil || errB != nil {
		t.Errorf("packed map presence: Deno=%v Go=%v", errA, errB)
		return
	}
	left, err := testkit.OpenMPQ(a)
	if err != nil {
		t.Fatal(err)
	}
	right, err := testkit.OpenMPQ(b)
	if err != nil {
		t.Fatal(err)
	}
	if left.HeaderOffset != right.HeaderOffset || !bytes.Equal(a[:left.HeaderOffset], b[:right.HeaderOffset]) {
		t.Error("packed map header before the archive differs")
	}
	// The archive header's fixed fields: its size, the format version with the sector size, and both table lengths.
	// The archive size and the table offsets depend on the compressor.
	for _, field := range [][2]int{{4, 8}, {12, 16}, {24, 32}} {
		if !bytes.Equal(a[left.HeaderOffset+field[0]:left.HeaderOffset+field[1]], b[right.HeaderOffset+field[0]:right.HeaderOffset+field[1]]) {
			t.Errorf("packed map archive header differs in bytes %d to %d", field[0], field[1])
		}
	}
	listA, err := left.Listfile()
	if err != nil {
		t.Fatal(err)
	}
	listB, err := right.Listfile()
	if err != nil {
		t.Fatal(err)
	}
	if !slices.Equal(listA, listB) {
		t.Errorf("packed map file list/order differs: Deno=%q Go=%q", listA, listB)
	}
	if left.Blocks != right.Blocks || left.Blocks != len(listA)+1 {
		t.Errorf("packed map block count: Deno=%d Go=%d list=%d", left.Blocks, right.Blocks, len(listA))
	}
	for _, name := range append(listA, "(listfile)") {
		contentA, foundA, errA := left.Read(name)
		contentB, foundB, errB := right.Read(name)
		if errA != nil || errB != nil {
			t.Fatalf("MPQ read %s: %v / %v", name, errA, errB)
		}
		if !foundA || !foundB || !bytes.Equal(contentA, contentB) {
			t.Errorf("packed map content differs: %s", name)
		}
	}
	// Compressor-dependent stored lengths/offsets cannot be equal. Compare every hash slot (including the block
	// index, so actual archive order is checked) and every block's uncompressed length/flags instead.
	hashA, blockA := archiveTables(a, left.HeaderOffset)
	hashB, blockB := archiveTables(b, right.HeaderOffset)
	if !slices.Equal(hashA, hashB) {
		t.Error("packed map hash slots or block indices differ")
	}
	if !slices.Equal(blockA, blockB) {
		t.Error("packed map uncompressed block sizes or flags differ")
	}
}

func archiveTables(data []byte, offset int) (hashes, blocks []uint32) {
	header := data[offset : offset+32]
	le := binary.LittleEndian
	table := func(at, count, key uint32) []uint32 {
		words := make([]uint32, count)
		for i := range words {
			words[i] = le.Uint32(data[offset+int(at)+i*4:])
		}
		mpq.DecryptBlock(words, key)
		return words
	}
	hashes = table(le.Uint32(header[16:]), le.Uint32(header[24:])*4, mpq.HashTableKey)
	entries := table(le.Uint32(header[20:]), le.Uint32(header[28:])*4, mpq.BlockTableKey)
	for i := 0; i < len(entries); i += 4 {
		blocks = append(blocks, entries[i+2], entries[i+3])
	}
	return hashes, blocks
}

func copyTree(t *testing.T, from, to string, keep func(string) bool) {
	t.Helper()
	err := filepath.WalkDir(from, func(path string, entry os.DirEntry, err error) error {
		if err != nil {
			return err
		}
		rel, err := filepath.Rel(from, path)
		if err != nil {
			return err
		}
		rel = filepath.ToSlash(rel)
		if rel != "." && keep != nil && !keep(rel) {
			if entry.IsDir() {
				return filepath.SkipDir
			}
			return nil
		}
		target := filepath.Join(to, filepath.FromSlash(rel))
		if entry.IsDir() {
			return os.MkdirAll(target, 0o777)
		}
		data, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		return os.WriteFile(target, data, 0o666)
	})
	if err != nil {
		t.Fatal(err)
	}
}

func appendFile(t *testing.T, root, name, text string) {
	t.Helper()
	data, err := os.ReadFile(filepath.Join(root, name))
	if err != nil {
		t.Fatal(err)
	}
	testkit.WriteFile(t, root, name, append(data, []byte(text)...))
}

func settingsMap(t *testing.T, root string) {
	for _, name := range []string{"war3map.w3i", "war3map.lua"} {
		testkit.WriteFile(t, root, "maps/map.w3x/"+name, testkit.Fixture(t, "map-settings-v39/"+name))
	}
}

const everySetting = `settings {
  info { name = "Conformance"; author = "Moonwell"; description = "All settings"; recommendedPlayers = "1–2" }
  loadingScreen { background = -1; model = "Models/custom.mdx"; text = "Loading"; title = "Title"; subtitle = "Subtitle" }
  gameplay { heroMaxLevel = 25; foodLimit = 200 }
  players { ["0"] { name = "Computer"; controller = "computer"; race = "orc"; fixedStart = false; x = 256; y = -512 } }
  forces { ["0"] { name = "Team"; allied = false; alliedVictory = true; sharedVision = false; sharedControl = true; sharedAdvancedControl = true } }
  environment {
    soundEnvironment = "Mountains"
    waterColor = List(10, 20, 30, 255)
    fog { enabled = true; style = 1; start = 100; end = 1000.5; density = 0.75; color = List(3, 4, 5, 255) }
  }
  gameplayConstants { ["Misc"] { ["DefenseArmor"] = "0.05" } }
  gameInterface { ["CustomSkin"] { ["Test"] = "value" } }
}
`

const everyObject = `amends "@moonwell/ObjectFile.pkl"
heroes { ["paladin"] { id = "H001"; base = "Hpal"; name = "Hero"; properties { ["uhpm"] = 900 } } }
units { ["footman"] { id = "h001"; base = "hfoo"; name = "Footman" } }
buildings { ["barracks"] { id = "h002"; base = "hbar"; name = "Barracks" } }
items { ["claws"] { id = "I001"; base = "ratf"; name = "Claws" } }
abilities { ["light"] { id = "A001"; base = "AHhb"; name = "Holy Light"; levels = 2; manaCost = List(10, 20) } }
buffs { ["blizzard"] { id = "B001"; base = "BHbd"; nameEditorOnly = "Blizzard"; tooltip = "Cold" } }
upgrades { ["swords"] { id = "R001"; base = "Rhme"; name = List("Swords I", "Swords II"); levels = 2 } }
`

func TestNormalizationIsNarrow(t *testing.T) {
	root := filepath.Join("C:", "temporary", "map")
	if got := normalize("Run deno task build, test or dev. "+root, root); got != "Run moonwell build, test or dev. <project>" {
		t.Fatal(got)
	}
	value := "warning: valuable\n  indent\n\r\nhttps://host/deno taskless\n"
	if normalize(value, root) != value {
		t.Fatal("normalization removed unrelated bytes")
	}
}

// Guard the §6.2 inventory independently of optional tool availability.
func TestFixtureContract(t *testing.T) {
	if strings.Count(everySetting, " = null") != 0 {
		t.Fatal("every setting must be active")
	}
	for _, category := range []string{"heroes", "units", "buildings", "items", "abilities", "buffs", "upgrades"} {
		if !strings.Contains(everyObject, category+" {") {
			t.Fatal("missing category ", category)
		}
	}
}
